informatici/openhospital-gui

Dockerfile-oh
docker-compose.yml
startup.sh

This PR adds the OpenHospital Swing-based GUI to the Docker Compose file, so that one can run both database and GUI with a simple `docker-compose up`.  
Notes:
- I had to modify `startup.sh` because it wasn't working - several folders of those included in the Java classpath do not exist, and the one created by the Maven build (`/target/*`) are not present
- I only tested this on Linux (and I suspect there will be issues at using this on Windows since it uses X11 for graphics..)
- the Docker file for the GUI downloads and builds both core and gui with Maven. I guess it would be quicker to build if we published the Maven artifacts somewhere.
- running GUI applications in Docker is less than trivial, as you have to use a non-root user, and somehow map the X11 server configuration in the …

Execute OpenHospital GUI with Docker compose

---

src/org/isf/examination/gui/PatientExaminationEdit.java

This is to fix bug OP-126.
The issue only happens in java 1.6. In 1.8 it works without intervention.
I have now fixed the issue for 1.6 as per the suggestion here:
https://stackoverflow.com/questions/455753/jtextarea-very-small-size-with-long-text/455777
I have also confirmed that the newly added code still works in java 1.8.
Please

OP-126 list box

---

src/org/isf/malnutrition/gui/InsertMalnutrition.java
src/org/isf/malnutrition/gui/MalnutritionBrowser.java
src/org/isf/medicals/gui/MedicalBrowser.java
src/org/isf/medicals/gui/MedicalEdit.java
src/org/isf/medicalstock/gui/MovStockBrowser.java
src/org/isf/medicalstock/gui/MovStockMultipleCharging.java
src/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
src/org/isf/medicalstockward/gui/WardPharmacy.java
src/org/isf/medicalstockward/gui/WardPharmacyEdit.java
src/org/isf/medicalstockward/gui/WardPharmacyNew.java
src/org/isf/medicalstockward/gui/WardPharmacyRectify.java
src/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowser.java
src/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowserEdit.java
src/org/isf/medtype/gui/MedicalTypeBrowser.java
src/org/isf/medtype/gui/MedicalTypeBrowserEdit.java
src/org/isf/menu/gui/GroupEdit.java
src/org/isf/menu/gui/Login.java
src/org/isf/menu/gui/MainMenu.java
src/org/isf/menu/gui/PrivilegeTree.java
src/org/isf/menu/gui/UserBrowsing.java
src/org/isf/menu/gui/UserEdit.java
src/org/isf/menu/gui/UserGroupBrowsing.java
src/org/isf/priceslist/gui/PricesBrowser.java
src/org/isf/serviceprinting/gui/MedicalPrintSelection.java
src/org/isf/serviceprinting/gui/MedicalStockSelection.java
src/org/isf/therapy/gui/TherapyEdit.java
src/org/isf/therapy/gui/TherapyEntryForm.java
src/org/isf/utils/jobjects/JTextFieldSearchModel.java
src/org/isf/xmpp/gui/CommunicationFrame.java

The pull request move Manager to Spring bean instead of manually create new instance.
Furthermore, moved Manager declaration as class attribute instead of method scope declaration.
This avoids declaring the same Manager multiple times in different methods of the same Class and easily understanding which Manager the class depends on.
The result is the same beacause in Spring a bean is Singleton by default, so every time we request it we would always have the same instance.

OP-111 Defined Managers of M modules as Spring Bean #time 1h

---

pom.xml
src/org/isf/gui/BaseComponent.java
src/org/isf/utils/image/ImageUtil.java
src/org/isf/video/PhotoboothTester.java
src/org/isf/video/gui/BottomPanel.java
src/org/isf/video/gui/PatientPhotoPanel.java
src/org/isf/video/gui/PhotoFrame.java
src/org/isf/video/gui/PhotoPanel.java
src/org/isf/video/gui/PhotoPreviewBox.java
src/org/isf/video/gui/PhotoboothComponent.java
src/org/isf/video/gui/PhotoboothComponent.jfd
src/org/isf/video/gui/PhotoboothComponentImpl.java
src/org/isf/video/gui/PhotoboothDialog.java
src/org/isf/video/gui/PhotoboothPanelModel.java
src/org/isf/video/gui/PhotoboothPanelPresentationModel.java

* OP-139: Upgrading to processing core 2.2.1
Version 1.2.1 cant be accessed from cytoscape repo anymore
* OP-139: Using webcam-capture library to capture image from webcam
* The old library (processing-core, etc) is not working as expected. So switching to this new library which seems to work
* OP-139: Added resolution selector on the photobooth frame
* OP-139: Fixing image resolution change implementation
* OP-139: Minor UI restructure
* Also get rid of 'discard' image button. Quite frankly, it is useless.
* OP-139: Fixing memory leak bug
* Need to make sure that the resolution property change listener is removed when closing photo dialog.
* This also fix the issue where there can be multiple listener listening to the change in resolution combo box, and hence causing issue where the …

OP-139: Upgrading to processing core 2.2.1 (#66)

---

README.md

Remove note about `mvn` version 3.2.5 begin required now that JDK 8 is used.
See Maven [release history](https://maven.apache.org/docs/history.html) to see that the most recent version can be used and is only dependent on JDK 7.

Remove note about mvn 3.2.5 now that JDK 8 is used

---

src/main/java/org/isf/medicals/gui/MedicalBrowser.java
src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
src/main/java/org/isf/menu/gui/Login.java
src/main/java/org/isf/menu/gui/MainMenu.java
src/main/java/org/isf/menu/gui/Menu.java
src/main/java/org/isf/xmpp/gui/ChatMessages.java
src/main/java/org/isf/xmpp/gui/ChatTab.java
src/main/java/org/isf/xmpp/gui/CommunicationFrame.java

Non-constant concatenations in logging messages are evaluated at runtime even when the logging message is not logged; this can negatively impact performance. Thus these changes use a parameterized log message instead which will not be evaluated when logging is disabled.
Because there were only 9 files, reformatting to match the standards was done.
If you want to hide the white space changes:

Replace concatenation with parameterized log message

---

pom.xml

Update Spring to latest 4.3.28 reversion that is compatible.  This matches the change made to the CORE repository. 
This also replaces this [PR](https://github.com/informatici/openhospital-gui/pull/192).

Update Spring from 4.3.18 to latest 4.x branch 4.3.28

---

bundle/language_ar.properties
bundle/language_de.properties
bundle/language_en.properties
bundle/language_es.properties
bundle/language_fr.properties
bundle/language_it.properties
bundle/language_pt.properties
bundle/language_sw.properties
bundle/language_zh_CN.properties

Adding the OP-248 email validation messages in the bundles.
Sibling PR: https://github.com/informatici/openhospital-core/pull/190

OP-248 Adding bundle message for email validation

---

src/main/java/org/isf/menu/gui/Menu.java

Strictly speaking I'm not sure why that java version check is there: if the version isn't right, it wouldn't be able to execute the bytecode at all, no? If so, should I remove that check?

Java version check update

---

startup.sh

- Updated syntax, comments, environment variables
- The script is now independent from file system location (you don't need to be in the OpenHospital installation dir to launch the software)
- Tested on Ubuntu 20.04 x64 - OpenJRE 14 - MariaDB 10.3

Update startup script - startup.sh

---

README.md
SetupGSM.sh
build.properties
doc/changelog_1_7_0.txt
doc/changelog_1_8_0.txt
doc/changelog_1_8_3.txt
rsc/generalData.properties
src/main/java/org/isf/menu/gui/MainMenu.java
src/main/java/org/isf/menu/gui/Menu.java
src/main/java/org/isf/utils/jobjects/BusyState.java
startup.sh

Mainly change text references from `OpenHospital` to `Open Hospital`.   In the process fixed a little grammar too.

Chore: fix project name references

---

pom.xml

following Spring notice:
https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020
Paired with informatici/openhospital-core#248.

Removing repo-spring-io

---

src/main/java/org/isf/hospital/gui/HospitalBrowser.java

Fix for OP-328 **Optimistic lock exception** being thrown When updating Hospital twice without closing the window (Edit → Update → Edit → Update).
Depends on [core-changes](https://github.com/informatici/openhospital-core/pull/250
)
@mwithi The case name might need to be updated to reflect the issue mentioned in the comment section of the case

OP-328 fix optimistic lock exception

---

pom.xml

Current address is secure: https://www.dcm4che.org/maven2/

Chore: update Dcm4Che Repository address to use https

---

src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java

Found with SpotBugs and I reported as a review comment on [PR 175](https://github.com/informatici/openhospital-gui/pull/175).
The method parameter is assigned to itself and then used only once in the last line of the method.

Chore: remove self assignment of variable

---

src/main/java/org/isf/priceslist/gui/PriceModel.java

Remove the redundant interface declaration as `AbstractTreeTableModel` already implements `TreeTableModel `.
Found with Intellij's Analyze plugin looking for redundant code.

Chore: remove redundant interface declaration

---

src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
src/main/java/org/isf/lab/gui/LabBrowser.java
src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowser.java
src/main/java/org/isf/medtype/gui/MedicalTypeBrowser.java
src/main/java/org/isf/opd/gui/OpdBrowser.java
src/main/java/org/isf/opd/gui/OpdEditExtended.java
src/main/java/org/isf/operation/gui/OperationRowOpd.java
src/main/java/org/isf/opetype/gui/OperationTypeBrowser.java
src/main/java/org/isf/patient/gui/PatientBrowser.java
src/main/java/org/isf/patvac/gui/PatVacBrowser.java
src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
src/main/java/org/isf/xmpp/gui/CommunicationFrame.java

I only removed the most **obvious** redundant type casts: where the cast matched the type of the object exactly (either defined that way or returned from a method call).   There are many redundant casts that are more subtle.

Chore: remove redundant cast where cast is the same as the variable is defined

---

src/main/java/org/isf/therapy/gui/TherapyEdit.java

The only references are:
````
private ArrayList<Double> qtyArray = new ArrayList<Double>();
if (qtyArray != null) qtyArray.clear();
if (qtyArray != null) qtyArray.clear();
````
And thus the code can be removed.
Found with IntelliJ's Analyze plugin.

Chore: remove qtyArray as defined but never queried

---

src/main/java/org/isf/utils/jobjects/JLabelRequired.java

When "fixing" naming issues came across the variable `MARK` that had the style of a constant but wasn't `static final`.  In the process of reviewing the code to see if if fact `MARK` was a constant noticed that the class was called once and only once by `org.isf.supplier.gui.SupplierEdit` when creating a new supplier. 
Removed unnecessary methods that just called super as they weren't used; added some Javadoc, and made some other small improvements. 
Made the changes; rebuilt the project, ran the GUI and saw that the "add new supplier" still functioned properly.

Chore: simplify JLabledRequired

---

src/main/java/org/isf/dicom/gui/FileDicomFilter.java
src/main/java/org/isf/utils/jobjects/OhTableModel.java
src/main/java/org/isf/utils/jobjects/OhTableModelExam.java
src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java

Found with IntelliJ Analyze migration aids inspection.
Use `contains()` instead of `indexOf()`; if nothing else it is more descriptive of the purpose of the test.
I got carried away and did some "reformatting" in the process.

Chore: use contains() instead of indexOf()

---

pom.xml

Temporary workaround for dcm4che servers disruption.
These disruptions are frequent. OP-347 is aimed to permanently solve this kind of issues by getting rid of dcm4che libraries.
**NOTE**: delete/move previous downloaded libs in your .m2 local repository
**WARNING**: This PR is linked to https://github.com/informatici/openhospital-core/pull/359 and so checks will fail if not merged first. Test it locally.

fix: workaround dcm4che repo service disruption

---

src/main/java/org/isf/examination/gui/PatientExaminationEdit.java

Instead of concatenation use `append()` and there is no need to convert `this.bmi` as StringBuilder handles the conversion to text.

Chore: remove concatenation in StringBuilder

---

rsc/txtPrinter.properties
rsc/xmpp.properties

`information` is plural; no need to add `s`.
There is another [PR](https://github.com/informatici/openhospital-doc/pull/37) that fixed the documentation.

Chore: information is plural

---

src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java

Original change was to "unbox" already "boxed" item:  `new Integer(origin.getSupId())` as `origin.getSupId()` returns an `Integer` object thus no need to create another `Integer` object (see line 1250).
Decided to change strings of length one to character objects as there may be an performance benefit in some cases.
Found with IntelliJ's Analyze plugin.

Chore performance

---

src/main/java/org/isf/lab/gui/LabNew.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
src/main/java/org/isf/operation/gui/OperationRowAdm.java
src/main/java/org/isf/operation/gui/OperationRowOpd.java

See OP-497.
Note the spacing appears to be inconsistent and that is because these files use multiple formatting techniques.  A reformat of the entire file to match standards is the real answer.

OP-497 Standardized on slf4j.Logger

---

src/main/java/org/isf/lab/gui/LabNew.java

There is no need to call jTableExams.updateUI when updating the selected laboratory material value. 
Commenting out the updateUI call resolves the NPE while changing the selection in table.

OP-431 NPE and Validation error on Exam selection and saving

---

src/main/java/org/isf/therapy/gui/TherapyEdit.java

The method `visColums` is wrong (trying to find a bundle key for a formatted date) and is not even used so it should be removed.

Chore: remove unused and incorrect method

---

src/main/java/org/isf/admission/gui/AdmissionBrowser.java

This file had various and different formatting styles.  It appears that some of which was caused by removing blocks of code with comments (now removed).
The only significant code changes were adding the ".msg" suffix to two property bundle keys to match the most recent push of language_en.properties.

Chore: reformat large sections of code

---

src/main/java/org/isf/utils/jobjects/MessageDialog.java

- Make all dialolgs accept both `getMessage()` and `formatMessage()` type messages.
- Add method to display all exception messages in the same format and reduce duplicate code.

Chore: improvements to MessageDialog class

---

src/main/java/org/isf/exatype/gui/ExamTypeEdit.java

When checking for strings that should be in a resource bundle, found this misplaced quote.

Chore: fix bad quote location

---

src/main/java/org/isf/dicom/gui/ShowPreLoadDialog.java

Comparing to zero means that the title always read, Loading multiple images: ", even when there was a single image.

Chore: fix the comparison

---

src/main/java/org/isf/utils/jobjects/MessageDialog.java

The `showExceptions()` method was looking up the message text in the resource bundle even though the exception processing already did it.

Chore: fix showExceptions()

---

src/main/java/org/isf/supplier/gui/SupplierEdit.java

Got carried away with search/replace adding the colons; the Required Field message doesn't need it

Chore: remove unneeded colon after Required Fields msg

---

pom.xml

Fixing this will make all the license headers look the same.

Chore: put project description all on one line so it doesn't wrap in header comment

---

src/main/java/org/isf/therapy/gui/TherapyEntryForm.java
src/main/java/org/isf/visits/gui/VisitView.java

Need to call pack() on the dialog before showing it, especially when we are adding components to the panel / dialog.
This will cause the window to be calculated & painted properly. Otherwise some components wont be shown properly.

OP-630: fixing rendering issue on Therapy dialog

---

src/main/java/org/isf/medstockmovtype/gui/MedicalsrMovPatList.java

What started out as just using a bulk method, `addAll()` turned into removing a unused variable and fixing the name of another class variable so it didn't start with an uppercase `J`.

Chore: use bulk method instead of iteration for performance

---

src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
src/main/java/org/isf/operation/gui/OperationRowBase.java

Think this should be the last of the hard coded date/time string patterns.

Chore: use date constant strings in org.isf.utils.Constants instead of strings or local constants

---

src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java

Pharmacy -> Pharmaceutical Stock -> StockCard button -> Cancel button
Generates a NPE
<pre>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.isf.utils.time.Converters.convertToLocalDateTime(Converters.java:46)
at org.isf.utils.jobjects.StockCardDialog.getLocalDateTimeFrom(StockCardDialog.java:155)
at org.isf.medicalstock.gui.MovStockBrowser.lambda$getStockCardButton$0(MovStockBrowser.java:269)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
</pre>
Execute the conversion of dates only when Cancel is not selected.
Similar problem with Pharmacy -> Pharmaceutical Stock -> Stock Ledger button -> Cancel button

Chore: fix NPE when Cancel button in dialog is used

---

src/main/java/org/isf/utils/jobjects/GoodDateTimeChooser.java

Add spinner option to time picker.
Fix issue where the minute, second, and nanosecond values were zeroed out.

Chore: add spinner option to time picker; do not change specified time

---

src/main/java/org/isf/opd/gui/OpdEdit.java

This is when creating a new OPD entry when `OPDEXTENDED=no` in the settings file

Chore: remove GregorianCalendar usage

---

src/main/java/org/isf/accounting/gui/BillBrowser.java
src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
src/main/java/org/isf/lab/gui/LabBrowser.java
src/main/java/org/isf/medicals/gui/MedicalBrowser.java
src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
src/main/java/org/isf/opd/gui/OpdBrowser.java
src/main/java/org/isf/patvac/gui/PatVacBrowser.java
src/main/java/org/isf/stat/gui/DiseasesListLauncher.java
src/main/java/org/isf/stat/gui/ExamsList1Launcher.java
src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
src/main/java/org/isf/visits/gui/VisitView.java

This PR attempts to address all the top level windows from the main startup menu.    The changes include adding wrapping to button bars and setting minimum window sizes where needed.   In addition a few windows are no longer re-sizable.  I also took this opportunity to remove explicit bounds setting for the windows using Toolkit.
The nice formatting that I attempted is lost; so here is screenshot
Text only version:
Windows in order of the menu                          Changes
OPD                                                                   2
Pharmacy
Pharmaceuticals                                          1, 2, 4
Pharmaceutical Stock                                  1, 2, 4
Pharmaceutical Stock Ward                         2, 4
Admission/Patient …

OP-905 improve resizing and wrapping of button bar

---

bundle/language_en.properties
src/main/java/org/isf/sms/gui/SmsBrowser.java
src/main/java/org/isf/sms/gui/SmsEdit.java
src/main/java/org/isf/utils/jobjects/GoodDateTimeToggleChooser.java

See OP-927
Increased the width of the date fields so both the date and time are visible by default.
Also centered the buttons on the New dialog to match other dialogs.

OP-927 update date and time choosers for SMS Manager and New SMS

---

src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java

What the TODO was referencing is already done; needs to be removed.

Chore: remove TODO left in the code

---

src/main/java/org/isf/medicals/gui/MedicalBrowser.java
src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java

See OP-943
Fixes the `contains()` test by using the longer string to test; `.xls` is also a part of `.xlsx`.   Sorry.

OP-943 honor the Excel file extension and use matching exporting code

---

src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java

See OP-917  this addresses only the Pharmacy → Pharmaceutical Stock Ward → Drugs [tab] after the New button is used.
This is a bit heavy handed but after trying multiple options of reevaluate, invalidate, repaint, resetting the column widths, etc. nothing else worked.

OP-917 fix rendering of Rectify button

---

src/main/java/org/isf/medicals/gui/MedicalBrowser.java
src/main/java/org/isf/medicals/gui/MedicalEdit.java

See OP-942
After seeing the fix in https://github.com/informatici/openhospital-gui/pull/1287 and the related discussion I went back and found a better solution for this issue that better honors the lock variable.
After update immediately set the lock variable in the current in memory table to the value just changed.
If this is OK I will redo the hotfix version too.

OP-942 Better handling of multiple updates

---

src/main/java/org/isf/accounting/gui/BillBrowser.java
src/main/java/org/isf/accounting/gui/PatientBillEdit.java
src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
src/main/java/org/isf/lab/gui/LabBrowser.java
src/main/java/org/isf/lab/gui/LabEdit.java
src/main/java/org/isf/lab/gui/LabEditExtended.java
src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java

See [OP-974](https://openhospital.atlassian.net/browse/OP-974).
Paired with https://github.com/informatici/openhospital-core/pull/776.
Cc: @emecas, @vir8wh47, @robertoc223388

OP-974 transactional methods in manager not catching runtime exceptions

---

src/main/java/org/isf/exa/gui/ExamBrowser.java

See OP-983
Needed to recreate the `sorter` object and reattach it to the `table` when a change was made

OP-983 fix index out of bounds when filtering the list

---

src/main/java/org/isf/admission/gui/PatientFolderBrowser.java

See OP-723
After fix: Admission/Patient -> pick patient with multiple OPD and Wards -> Clinical Sheet should look like:

OP-723 fix fetching wards in clinical sheet; row number needs adjustment

---

src/main/java/org/isf/lab/gui/LabNew.java

See OP-988
Note: could not use `indexOf()` to find the row because values could be null and the `equals()` in `Laboratory` doesn't handle null cleanly.

OP-988 ensure result is set for procedure type 1

---

bundle/language_en.properties
src/main/java/org/isf/hospital/gui/HospitalBrowser.java

Because `startTime` and `endTime` are `LocalTime` objects the hour value ***must*** be in the range of 0 to 24 inclusive thus this test is not needed.

Chore: remove test as LocalTime object must be in range of 0 to 24

---

src/main/java/org/isf/medicals/gui/MedicalEdit.java

See OP-996
Also moved definition of `newMedical` to make the scope of the variable more clear.

OP-996 use correct variable in updateMedial() call

---

pom.xml

Note this doesn't include the update to Spring 6 but does increment the Spring 5 version to latest 5.3.24

Chore: combine all recent dependabot jar updates to match changes in Core repo

---

rsc/dicom.properties.dist
src/main/java/org/isf/dicom/gui/DicomViewGui.java

See OP-981.
Fixed also an unwanted exception due to imageInputStream already closed by the `read()`.
Paired with https://github.com/informatici/openhospital-core/pull/857.

OP-981 dicom series for jpegs

---

src/main/java/org/isf/opd/gui/OpdEditExtended.java

See OP-1028
Reproduce by blanking out the time widget for a new visit.

OP-1028 include test for missing hour value too

---

.ide-settings/eclipse/OpenHospital-Java-CodeStyle-Formatter.xml
bundle/language_en.properties
src/main/java/org/isf/accounting/gui/PatientBillEdit.java
src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
src/main/java/org/isf/patient/gui/SelectPatient.java

See OP-1025.
Changes:
- removed unnecessary class fields and mostly using `this.thisBill` as main object
- separated methods for model changes and GUI changes
- first initialize data, then initialize components, then update components anytime needed after data changes
- add check on prices changes
- reusing the code
- overall formatting
Please test it thoroughly 🙂

OP-1025 separate business logic from gui in patient bill edit

---

src/main/java/org/isf/patvac/gui/PatVacEdit.java

After the `name` is built it is made lower cased in the next non-blank line:
<pre>
if (name.toLowerCase().contains(key.toLowerCase())) {
</pre>

Chore: remove toUpperCase() when everything is lower cased later

---

src/main/java/org/isf/lab/gui/LabEdit.java
src/main/java/org/isf/lab/gui/LabEditExtended.java

A new `LaboratoryForPrint` object was just added to `labs` thus the test is always true; that is `labs` is not empty.

Chore: remove useless if test; the list is always not empty

---

pom.xml

Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.27
This update fixes the following CVE:
[cve-2023-20863: Spring Expression DoS Vulnerability](https://spring.io/security/cve-2023-20863)
This matches the change in CORE: https://github.com/informatici/openhospital-core/pull/947

Chore: Update Spring to 5.3.27

---

pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.11
This release includes a fix for [CVE-2023-20873: Security Bypass With Wildcard Pattern Matching on Cloud Foundry](http://spring.io/security/cve-2023-20873).
This matches the change in the Core repo (see https://github.com/informatici/openhospital-core/pull/953)

Chore: Upgrade to Spring Boot 2.7.11

---

pom.xml

The surefire plugin in Core is already set to 3.1.0.
Clean rebuild and test.

Chore: combine recent dependabot jar updates to match changes in Core

---

src/main/java/org/isf/xmpp/gui/CommunicationFrame.java

Single character strings in `indexOf()` should be character literals.   There is a slight performance improvement.

Chore: replace string literal in indexOf() with single character

---

src/main/java/org/isf/utils/jobjects/JAgenda.java

`Integer.valueOf()` returns an `Integer` where as `Integer.parseInt()` returns an `int`

Chore: remove unneeded boxing

---

bundle/language_en.properties
src/main/java/org/isf/priceslist/gui/ListBrowser.java

Code inspection recommended using `+` instead of `concat()` when constants are involved.  The `better` fix is just to use the capabilities of the `formatMessage()` method.

Chore: use formatMessage() instead of concat()

---

src/main/java/org/isf/xmpp/gui/CommunicationFrame.java

There is no need to specify an import for a class in the same package.

Chore: remove import statement for class in same package

---

src/main/java/org/isf/opd/gui/OpdBrowser.java

It has the advantage of not needing boxing/unboxing of value.   `Integer.parseInt()` has used in the same file in other locations.

Chore: use Integer.parseInt() for String to int conversion

---

src/test/java/org/isf/accounting/gui/BillDataLoaderTest.java
src/test/java/org/isf/accounting/gui/totals/BalanceTotalTest.java
src/test/java/org/isf/accounting/gui/totals/PaymentsTotalTest.java
src/test/java/org/isf/accounting/gui/totals/UserTotalTest.java
src/test/java/org/isf/admission/gui/DiseaseFinderTest.java
src/test/java/org/isf/admission/gui/validation/OperationRowValidatorTest.java
src/test/java/org/isf/admission/gui/ward/WardComboBoxInitializerTest.java
src/test/java/org/isf/exa/gui/ExamFilterFactoryTest.java
src/test/java/org/isf/lab/gui/elements/ExamComboBoxTest.java
src/test/java/org/isf/lab/gui/elements/ExamRowComboBoxTest.java
src/test/java/org/isf/lab/gui/elements/ExamRowSubPanelTest.java
src/test/java/org/isf/lab/gui/elements/MatComboBoxTest.java
src/test/java/org/isf/lab/gui/elements/PatientComboBoxTest.java
src/test/java/org/isf/utils/image/ImageUtilTest.java

JUnit5 is more tolerant regarding the visibilities of Test classes than JUnit4, which required everything to be public.
In this context, JUnit5 test classes can have any visibility but private, however, it is recommended to use the default package visibility, which improves readability of code.
Also used more typical method (or more `geeky`) calls in many cases; for example, used `.hasSize()`

Chore: JUnit improvements

---

src/main/java/org/isf/admission/gui/PatientDataBrowser.java

A previous PR moved the definition of `List<Ward> ward` from a class instance to a local variable.  With it being local it is now obvious that the variable `ward` is not used.   Looking at the git history, this piece of code has been this way since moving to github since 2015.   It is just not needed.

Chore: remove unused code

---

src/main/java/org/isf/lab/gui/LabBrowser.java

The variable `pfrmHeight` is only used once in a `new Dimension(225, pfrmHeight)` statement.   It didn't have assigned value and zero (the default) seems to work;   I tested with multiple values for `pfrmHeight` and 100 seems reasonable.   It could stay the way it is but it just looks funny/wrong IMHO.

Chore: provide init value for variable

---

src/main/java/org/isf/admission/gui/AdmissionBrowser.java

The variable `patientBrowserManager` is never used and the assignment to `self` is never used again

Chore: remove unused variable and assignment

---

src/main/java/org/isf/accounting/gui/BillBrowser.java

The variable, `medicalJTextField` was previously used in a panel but the panel was removed leaving this variable defined, set, and never used.
The methods, `getPatientParent` and `setPatientParent` were never accessed.

Chore: remove unused code and methods

---

src/main/java/org/isf/utils/jobjects/Cropping.java

The nested class `ClipMover` is never referenced; remove from the code base.

Chore: remove unused nested class

---

src/main/java/org/isf/lab/gui/ExamPicker.java

First the method, `getSelectedObject()` is never called from any code.   Removing that method means the private method, `getSelectedRow()` is never referenced.  Removing that method means the method, `setSelectedRow()` is not needed as there isn't a way to reference the private variable,  `selectedRow` except by name which isn't done.   
Also removed fully qualified package names in the body of the code.

Chore: code cleanup and remove unused methods

---

bundle/language_en.properties
src/main/java/org/isf/visits/gui/VisitView.java

See OP-1126
Added "\<select a ward\>" message to initial ward combo box instead of blank.  Changed the behavior slightly as the old behavior when the "blank" entry was selected again after selecting a specific ward, all visits for all wards would be displayed; now, there is another entry "\<all wards\>" that can do  the same thing and selecting "\<select a ward\>" returns the dialog back to its original empty state.    This seems more consistent and understood behavior instead of "\<select a ward\>" meaning something different the first time and when used later.
I will update the documentation after this is committed.

OP-1126: add helpers in Worksheet

---

src/main/java/org/isf/admission/gui/PatientFolderBrowser.java

Defining a local variable in a `try` block and then not using it has no value.
Looking at the class history, the variable `ward` was originally a class variable that was used to fill a column in the table.  With time the column was modified to include `OPD` and the class variable was no longer used.  In another PR class variables that were used only locally were made into local variables and that is how this particular local was born.
Removing this code has no effect.

Chore: remove unused variable/code

---

src/main/java/org/isf/admission/gui/PatientFolderBrowser.java

Discovered while testing OP-782.

Chore: small refactoring

---

rsc/default_credentials.properties.dist
rsc/default_demo.credentials.properties.dist
src/main/java/org/isf/menu/gui/Login.java
src/main/java/org/isf/utils/jobjects/JLabelInfo.java

Implement OP-1141 by adding info with default credentials as a tool tip text in a button, and adopting a simple HTML format for presentation. 
Paired with: https://github.com/informatici/openhospital-core/pull/1256
Presenting the text is conditioned to the existent of `default_credentials.properties` file as a resource.
NOTE: since it's a temporary file and anyone can easily translate it, we are not caring about translations

OP-1141 Add info with default credentials

---

.ide-settings/eclipse/OpenHospital.importorder
.ide-settings/idea/OpenHospital-code-style-configuration.xml
pom.xml
rsc/version.properties
src/main/java/org/isf/Application.java
src/main/java/org/isf/menu/gui/Menu.java

See OP-1149
Note the **main** class is now `org.isf.Application` and not `org.isf.menu.gui.Menu`.   The reason for the change is because Spring Boot scans downward from the main class looking for beans, etc.
`ApplicationContext.xml` is no longer used (Spring has been moving away from xml files).  The information is now included in either `application.properties` or `application.yml`. Much of the information is gleaned from the class files themselves by scanning downward from the main class.
The CORE PR companion is:  https://github.com/informatici/openhospital-core/pull/1303

OP-1149 Update to Spring Boot 3.2.x
