informatici/openhospital-gui

- pom.xml
OP-65 Merging pull request #2 from matteoturra/master  …
Update pom.xml - testing results #time 1h #done
> Op 65 improve pom

- src/org/isf/medicalstock/gui/MovStockBrowser.java
- src/org/isf/medicalstockward/gui/WardPharmacy.java
Search fields was added in Pharmaceutical stock & Pharmaceutical Stock Ward to facilitate quick selection of medicals.
> Task OP-86 done (Uni2grow Cameroun)

- pom.xml
- src/org/isf/menu/gui/MainMenu.java
- src/org/isf/menu/gui/Menu.java
- src/org/isf/patient/gui/PatientInsertExtended.java
WIP in order to mend the 'gui' component to work with 'api' one (coming soon)
> refactoring for openhospital-api

- src/org/isf/admission/gui/AdmissionBrowser.java
- src/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/org/isf/admission/gui/PatientFolderBrowser.java
- src/org/isf/examination/gui/PatientExaminationEdit.java
- src/org/isf/exatype/gui/ExamTypeBrowser.java
- src/org/isf/exatype/gui/ExamTypeEdit.java
- src/org/isf/hospital/gui/HospitalBrowser.java
- src/org/isf/lab/gui/LabBrowser.java
- src/org/isf/lab/gui/LabEdit.java
- src/org/isf/opd/gui/OpdEditExtended.java
> Op 102 master refactoring for api

- pom.xml
- src/org/isf/gui/BaseComponent.java
- src/org/isf/utils/image/ImageUtil.java
- src/org/isf/video/PhotoboothTester.java
- src/org/isf/video/gui/BottomPanel.java
- src/org/isf/video/gui/PatientPhotoPanel.java
- src/org/isf/video/gui/PhotoFrame.java
- src/org/isf/video/gui/PhotoPanel.java
- src/org/isf/video/gui/PhotoPreviewBox.java
- src/org/isf/video/gui/PhotoboothComponent.java
- src/org/isf/video/gui/PhotoboothComponent.jfd
- src/org/isf/video/gui/PhotoboothComponentImpl.java
- src/org/isf/video/gui/PhotoboothDialog.java
- src/org/isf/video/gui/PhotoboothPanelModel.java
- src/org/isf/video/gui/PhotoboothPanelPresentationModel.java
Version 1.2.1 cant be accessed from cytoscape repo anymore
> OP-139: Upgrading to processing core 2.2.1

- bundle/language_ar.properties
- bundle/language_de.properties
- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- bundle/language_pt.properties
- bundle/language_sw.properties
- bundle/language_zh_CN.properties
- src/org/isf/lab/gui/LabBrowser.java
- src/org/isf/lab/gui/LabEdit.java
- src/org/isf/lab/gui/LabEditExtended.java
Pull request to add on exam page the button 'print' to print the exam result of one patient.
> OP-96 - print button inside labeditextended

- src/org/isf/accounting/gui/BillBrowser.java
- src/org/isf/accounting/gui/PatientBillEdit.java
Related to informatici/openhospital-api#19
8b142b4
5fa4f25
https://github.com/informatici/openhospital-core/pull/85
04d520a
> OP-205 Fixing GET to `/bills/{id}` End Point in GUI Project

- bundle/language_en.properties
- bundle/language_it.properties
- src/org/isf/dicom/gui/DicomGui.java
- src/org/isf/dicom/gui/DicomViewGui.java
the com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader
provided by dcm4che library was unstable
> Forced to use com.sun.imageio.plugins.jpeg.JPEGImageReader

- rpt/ProductLedgerWard_it.properties
* Translate /rpt/ProductLedgerWard.properties in it
translation completed for the source file '/rpt/ProductLedgerWard.properties'
on the 'it' language.
Co-authored-by: transifex-integration[bot] <43880903+transifex-integration[bot]@users.noreply.github.com>
> Translate '/rpt/ProductLedgerWard.properties' in 'it' (#168)

- pom.xml
About the issue with the `dpiaware` flag mentioned in [OP-226](https://openhospital.atlassian.net/browse/OP-226), I can't reproduce it since I don't own a high-dpi screen. And I'd suggest to survey whether this is a big issue with OH users.  
Anyway, there are some (awkward) [solutions out there](https://stackoverflow.com/a/39372897/153761), and apparently [the issue is solved in Java 9](https://stackoverflow.com/a/45426996/153761).
> [OP-226] Java 8

- .ide-settings/eclipse/OpenHospital-Java-CodeStyle-Formatter.xml
- .ide-settings/eclipse/OpenHospital.importorder
- .ide-settings/idea/OpenHospital-code-style-configuration.xml
- README.md
Add common IDE code style and import definitions and update `README.md` with installation instructions.
> Add IDE settings and update README.md

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
R getPatient(name) -> getPatientByName(name) (deprecated)
R getPatient(code) -> getpatientById(code)
R isPatientPresent(name) -> isNamePresent(name) (manager)
R isPatientPresent(name) -> isPatientPresentByName(name) (service)
> Some refactoring and deprecations

- src/main/java/org/isf/patient/gui/SelectPatient.java
'PAT_AFFILIATED_PERSON' and 'PAT_IS_HEAD_AFFILIATION' are not defined
> Removed unwanted method for not existing fields

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/sms/gui/SmsBrowser.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockCard.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEntryForm.java
- src/main/java/org/isf/utils/jobjects/OhTableDrugsModel.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
- src/main/java/org/isf/visits/gui/VisitView.java
Fixed date formatting by changing to formmater introduced in java 8. Previuosly used java.text.DateFormat couldn't parse java.time date formats
> OP-226 date formatter fix

- src/main/java/org/isf/ward/gui/WardBrowser.java
- src/main/java/org/isf/ward/gui/WardEdit.java
This is to fix OP-340 - Updating Ward more than once leads to error message saying 'The data has been updated by someone else'
> OP-340 Updating Ward fix

- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- bundle/language_pt.properties
- bundle/language_sw.properties
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
**Paired with https://github.com/informatici/openhospital-core/pull/254 (need its merge for the checks to pass)**
Found out that the @Transient weight property in Patient entity was used only (1 occurrence) in WardPharmacyNew, while @Transient height property never used.
Going to simplify Patient’s entity and to retrieve his/her weight only when needed.
> Op 262 contextualize weight and height

- bundle/language_ar.properties
- bundle/language_de.properties
- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- bundle/language_pt.properties
- bundle/language_sw.properties
- bundle/language_zh_CN.properties
- src/main/java/org/isf/visits/gui/InsertVisit.java
- src/main/java/org/isf/visits/gui/VisitView.java
Althoug the OP-349 has been moved to `PENDING` this PR includes some good improvement to the GUI.
> OP-349 missing font in report generation

- src/main/java/org/isf/visits/gui/VisitView.java
This it a companion fix to the push to Core for OP-403.  See https://github.com/informatici/openhospital-core/pull/288
> OP-403 Assign to visits instead of vsrows

- src/main/java/org/isf/disease/gui/DiseaseEdit.java
- src/main/java/org/isf/vaccine/gui/VaccineEdit.java
> OP-408 Fixing "The data has been updated by someone else”

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
Changed the date format passed to the report, to be tested (widely) for `Accounting \ Report` and `Pharmaceuticals \ Expiring` report
> OP-358 Date error in Accounting report

- src/main/java/org/isf/dicom/gui/ShowPreLoadDialog.java
Found with SpotBugs.    Remove double assignment as per OP-415.
> OP-417 remove double assignment

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
Found with SpotBugs.  
Remove unnecessary `if` statement as code is duplicated in both branches.
> OP-418 remove unnecessary if test

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
As described in OP-420, expand the null checks into separate conditionals to stop the possibility of NPEs.
Found with SpotBugs.
> OP-420 fix null checking

- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/PrivilegeTree.java
Remove unnecessary `contains()` method as described in OP-421.
> OP-421 remove unneeded contains() method

- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowEdit.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
Miscellaneous cleanups for OP-372 commit
> OP-372 misc cleanups

- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/menu/gui/Menu.java
- src/main/java/org/isf/priceslist/gui/PriceModel.java
- src/main/java/org/isf/priceslist/gui/PricesBrowser.java
- src/main/java/org/isf/pricesothers/gui/PricesOthersBrowser.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockCard.java
- src/main/java/org/isf/utils/jobjects/BusyState.java
Found with IntelliJ's Analyze plugin
> Chore: fix missorted modifiers into canonical order

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
See description of changes in OP-427.
Found with SpotBugs
> OP-427 remove useless object created

- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-429 equals between inconvertible types

- src/main/java/org/isf/lab/gui/LabNew.java
See description of changes in OP-42 as to the reasoning behind the changes..
Found with SpotBugs
> OP-428 dead code removal and code simplification

- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
See OP-441 for description of logic for removing field and method.
> OP-441 remove unwritten field and uncalled method

- src/main/java/org/isf/utils/jobjects/OhTableDrugsModel.java
See OP-442 for description of logic for removing the fields.
I also did some minor manual reformatting of the code without any other operational changes.
BTW, why is there a hardcoded FRENCH locale in this class?
````
final DateFormat currentDateFormat = DateFormat.getDateInstance(DateFormat.SHORT, Locale.FRENCH);
````
> OP-442 remove unread fields

- README.md
There were two broken links to the Jira issues/open issues which returned 500 error code after opening from the readme file.
> Fixes broken links to jira issues

- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/SubMenu.java
> OP-447 correct array declaration style

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowserEdit.java
- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/exa/gui/ExamRowEdit.java
- src/main/java/org/isf/exa/gui/ExamShow.java
- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/malnutrition/gui/InsertMalnutrition.java
- src/main/java/org/isf/malnutrition/gui/MalnutritionBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
- src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowser.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/opetype/gui/OperationTypeBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
> OP-448 remove pointless booleans

- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
See OP-457.
Until the corresponding [PR](https://github.com/informatici/openhospital-core/pull/346) in Core is committed these changes will fail.
> OP-457 use camel case names

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/help/HelpViewer.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/sms/gui/SmsEdit.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/utils/jobjects/JDateAndTimeChooserDialog.java
- src/main/java/org/isf/utils/jobjects/JFromDateToDateChooser.java
- src/main/java/org/isf/utils/jobjects/JTimeTable.java
- src/main/java/org/isf/utils/jobjects/VoDateTextField.java
- src/main/java/org/isf/utils/jobjects/VoLimitedTextArea.java
- src/main/java/org/isf/utils/jobjects/VoLimitedTextField.java
- src/main/java/org/isf/utils/time/DateTextField.java
See OP-454.
If a variable is a `constant` make it upper-case with `static final`.
If a variable is not a `constant` make it lower-case with Camel casing.
I also took the liberty of translating some Italian into English.
> OP-454 non-static non-final upper-case names

- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/menu/gui/UserBrowsing.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
> OP-461 remove redundant string operation

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
See OP-463
Remove collections/variables that were added to or cleared but never read.
Also a little reformatting/improvements; very minor.
> OP-463 remove unused collections/variables

- build.properties
- build.xml
> chore: rename 'mysql' dir to 'sql' in scripts

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
> OP-464 use isEmpty()

- src/main/java/org/isf/operation/gui/OperationEdit.java
See OP-465
The CI will fail until the Core [PR](https://github.com/informatici/openhospital-core/pull/360) is merged.
> OP-465 rename codeControl() to isCodePresent()

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/agetype/gui/AgeTypeBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/utils/jobjects/DateTextField.java
- src/main/java/org/isf/utils/time/DateTextField.java
> OP-469 use parseInt()

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
See OP-475
Got carried away and did a little reformatting to make things consistent.
> OP-475 remove unnecessary unboxing

- src/main/java/org/isf/menu/gui/Menu.java
See OP-474 as the reasoning behind the new testing method.
> OP-474 update version checking

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
See OP-476
In the process removed a parameter to a method that was no longer used; `protected BigDecimal askCost()` in WardPharmacyRectify.
> OP-476 remove unnecessary boxing

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/malnutrition/gui/InsertMalnutrition.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
> OP-469 Use parseType instead of valueOf

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/Menu.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/sms/gui/SmsBrowser.java
- src/main/java/org/isf/sms/gui/SmsEdit.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/utils/jobjects/JDateAndTimeChooser.java
- src/main/java/org/isf/utils/jobjects/JFromDateToDateChooser.java
- src/main/java/org/isf/utils/jobjects/JMonthYearChooser.java
- src/main/java/org/isf/utils/jobjects/JTextFieldSearchModel.java
- startup.cmd
- startup.sh
See OP-339
To be checked with https://github.com/informatici/openhospital-core/pull/372
> OP-339 resolve hard coded paths for configurations files

- src/main/java/org/isf/utils/jobjects/DateTextField.java
See OP-482
Made the change and tested it with the example given in the JIRA issue
> OP-482 set date to end of day for comparison

- bundle/language_ar.properties
- bundle/language_de.properties
- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- bundle/language_pt.properties
- bundle/language_sw.properties
- bundle/language_zh_CN.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-498 remove unused code/properties

- src/main/java/org/isf/hospital/gui/HospitalBrowser.java
> OP-328 Trying fixing the problem on GenaralData \ Hospital \ Edit button

- bundle/language_zh_CN.properties
Found with IntelliJ Analyze plugin.
> Chore: remove 4 properties found on in zh_CN properties file and not in code

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/menu/gui/Login.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/Menu.java
- src/main/java/org/isf/stat/gui/report/DiseasesList.java
- src/main/java/org/isf/stat/gui/report/ExamsList1.java
- src/main/java/org/isf/stat/gui/report/GenericReportAdmission.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/stat/gui/report/GenericReportDischarge.java
- src/main/java/org/isf/stat/gui/report/GenericReportExamination.java
- src/main/java/org/isf/stat/gui/report/GenericReportFromDateToDate.java
- src/main/java/org/isf/stat/gui/report/GenericReportMY.java
- src/main/java/org/isf/stat/gui/report/GenericReportOpd.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatient.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatientVersion2.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalOrder.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStock.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockCard.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockWard.java
- src/main/java/org/isf/stat/gui/report/GenericReportUserInDate.java
- src/main/java/org/isf/stat/gui/report/WardVisitsReport.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
- src/main/java/org/isf/xmpp/gui/ChatMessages.java
- src/main/java/org/isf/xmpp/gui/ChatTab.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
> OP-500 all loggers are private static final

- src/main/java/org/isf/utils/jobjects/MessageDialog.java
- src/main/java/org/isf/utils/layout/SpringUtilities.java
See OP-503.
FWIW, I have been using both classes for many days as part of the GUI changes.
> OP-503 new GUI helper classes

- bundle/language_en.properties
- src/main/java/org/isf/menu/gui/GroupEdit.java
- src/main/java/org/isf/menu/gui/PrivilegeTree.java
- src/main/java/org/isf/menu/gui/UserGroupBrowsing.java
See OP-508.
There is a corresponding CORE component: https://github.com/informatici/openhospital-core/pull/397
> OP-508 GUI changes for User and Groups browsers

- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
- src/main/java/org/isf/disease/gui/DiseaseEdit.java
- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/exa/gui/ExamEdit.java
- src/main/java/org/isf/exa/gui/ExamRowEdit.java
- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/stat/gui/DiseasesListLauncher.java
- src/main/java/org/isf/stat/gui/ExamsList1Launcher.java
- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
- src/main/java/org/isf/vactype/gui/VaccineTypeEdit.java
> OP-511 remove version number in window/dialog titles

- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/exa/gui/ExamShow.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/malnutrition/gui/MalnutritionBrowser.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowser.java
- src/main/java/org/isf/medtype/gui/MedicalTypeBrowser.java
- src/main/java/org/isf/operation/gui/OperationBrowser.java
- src/main/java/org/isf/operation/gui/OperationList.java
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
- src/main/java/org/isf/opetype/gui/OperationTypeBrowser.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
- src/main/java/org/isf/sms/gui/SmsBrowser.java
- src/main/java/org/isf/supplier/gui/SupplierBrowser.java
- src/main/java/org/isf/vaccine/gui/VaccineBrowser.java
- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
- src/main/java/org/isf/ward/gui/WardBrowser.java
> OP-512 standard form for "Please select a row." message

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
- src/main/java/org/isf/utils/jobjects/MessageDialog.java
Includes at least one common routine change.
> OP-513 Changes for Admission/Patient menu item

- bundle/language_en.properties
See OP-515 and https://github.com/informatici/openhospital-core/pull/402
> OP-515 resource bundle changes for Core version of OP-515

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
- src/main/java/org/isf/utils/jobjects/MessageDialog.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
See OP-517.
Also added logging to 2 classes instead of printing a stack trace to standard out and removed some commented out code that appears from the git commits to be there from the dawn of time.
> OP-517 Changes for Admission/Patient main menu item

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
- src/main/java/org/isf/disease/gui/DiseaseEdit.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowserEdit.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowserEdit.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowserEdit.java
- src/main/java/org/isf/exa/gui/ExamRowEdit.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
- src/main/java/org/isf/serviceprinting/gui/MedicalStockSelection.java
> OP-520: use MessageDialog.showExceptions() method

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
- src/main/java/org/isf/priceslist/gui/PriceModel.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/utils/jobjects/Cropping.java
- src/main/java/org/isf/utils/jobjects/OhTableDrugsModel.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
- src/main/java/org/isf/utils/jobjects/VoDateTextField.java
- src/main/java/org/isf/utils/time/DateTextField.java
- src/main/java/org/isf/video/gui/PhotoPreviewBox.java
- src/main/java/org/isf/video/gui/PhotoPreviewPanel.java
Where there was a need to generate output use Logger instead.    When it was just commented out code it was removed.
> Chore: remove System.out.println

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/gui/BaseComponent.java
- src/main/java/org/isf/medicals/gui/MedicalEdit.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medstockmovtype/gui/MedicalsrMovPatList.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/SplashWindow3.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/operation/gui/OperationList.java
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowEdit.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/utils/jobjects/DelayTimer.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
- src/main/java/org/isf/visits/gui/InsertVisit.java
- src/main/java/org/isf/xmpp/gui/ChatMessages.java
- src/main/java/org/isf/xmpp/gui/ChatTab.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
> OP-524 replace printStackTrace() calls

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
Lines 633-634 duplicated 630-631
> Chore: remove duplicated code

- bundle/language_en.properties
- src/main/java/org/isf/dicomtype/gui/DicomTypeEdit.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowserEdit.java
- src/main/java/org/isf/disease/gui/DiseaseEdit.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowserEdit.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowserEdit.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowserEdit.java
- src/main/java/org/isf/exa/gui/ExamEdit.java
- src/main/java/org/isf/exa/gui/ExamRowEdit.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
- src/main/java/org/isf/medicals/gui/MedicalEdit.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowserEdit.java
- src/main/java/org/isf/medtype/gui/MedicalTypeBrowserEdit.java
- src/main/java/org/isf/operation/gui/OperationEdit.java
- src/main/java/org/isf/opetype/gui/OperationTypeEdit.java
- src/main/java/org/isf/utils/jobjects/JTextFieldSearchModel.java
- src/main/java/org/isf/utils/jobjects/OhTableModel.java
- src/main/java/org/isf/utils/jobjects/OhTableModelExam.java
- src/main/java/org/isf/vaccine/gui/VaccineEdit.java
- src/main/java/org/isf/vactype/gui/VaccineTypeEdit.java
Only use "angal.common.description.txt"
> Chore: fix use of "angal.common.description" keys

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/BillItemPicker.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/stat/gui/report/GenericReportUserInDate.java
> OP-541 Standardize "accounting"

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/priceslist/gui/PriceModel.java
- src/main/java/org/isf/utils/jobjects/Cropping.java
- src/main/java/org/isf/utils/jobjects/MessageDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
See OP-523.  First part of changes required.
> OP-523 Part 1; first 11 files updated

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/dicom/gui/ShowPreLoadDialog.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/pricesothers/gui/PricesOthersEdit.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/therapy/gui/TherapyEntryForm.java
- src/main/java/org/isf/utils/jobjects/VoDateTextField.java
- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
- src/main/java/org/isf/video/gui/PhotoFrame.java
- src/main/java/org/isf/video/gui/PhotoboothComponent.java
> OP-523 Part 2

- bundle/language_en.properties
- src/main/java/org/isf/xmpp/gui/ChatMessages.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
Final part of finding strings.
Also fixed up the key suffixes and concatenation usage in the xmpp directory.
> OP-523 Part 3

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
What started as removing a seemingly infinite loop as described in OP-545 turned out to be more involved as the method return was never used or set and the confirmation dialog was really only a message dialog.   It appears that a merge of various PRs didn't go quite right.
> OP-545 fix what looks like an infinite loop

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/operation/gui/OperationEdit.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
See OP-544
Also added ".btn" suffix to the various JRadioButton key values.
> OP-544 remove JRadioButton shortcut keys

- src/main/java/org/isf/lab/gui/LabEdit.java
> OP-554 use equals() for objects

- bundle/language_en.properties
- src/main/java/org/isf/utils/jobjects/OhTableDrugsModel.java
> Chore: uppercase column headers in Drug Table Model

- rpt/MOH717_Monthly_Workload_Report_for_Hospitals_page1.properties
- rpt/OH008_lab_summary_for_opd.properties
- rpt/OH009_InPatientReport.jrxml
- rpt/OH010_OutPatientReport.jrxml
- rpt/OH010_OutPatientReport.properties
- rpt/PharmaceuticalStockWard.jrxml
- rpt/ProductLedger.jrxml
I made my best guess as to how fix the 8 issues outlined in OP-452.
I updated the jrxml file but **not** the jasper file.
I updated the base properties file but **not** en_properties files nor any other language.
Marking this as a work in progress so those more knowledgeable can review and comment (and create the required jasper files).
> OP-452 WIP resolved all the missing keys found in jrxml files

- bundle/language_fr.properties
See OP-542.  This is an update for French which primarily includes missing keys and some some consistency changes.
> OP-542 French resource bundle update

- bundle/language_es.properties
Strings with carriage returns are not always translated fully; this should fix that.
> OP-542 Found a few English words left over

- bundle/language_es.properties
Noticed the errors when looking at the file in Transifex
> Chore: two small fixes to Spanish text

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
- src/main/java/org/isf/utils/jobjects/MessageDialog.java
- src/main/java/org/isf/visits/gui/VisitView.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
No real code changes although I did translate some comments into English
> Chore: small spelling changes

- bundle/language_en.properties
Remove the comments from the English bundle
> Chore Remove the comments from the English bundle

- pom.xml
> OP-556 fix class not found exception with SkebbyGateway

- bundle/language_en.properties
> OP-559 change shortcut key to be unique

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
> OP-560 only attempt the deletion if the user says YES

- src/main/java/org/isf/opd/gui/OpdBrowser.java
> OP-562 Ensure there is a disease selected

- bundle/language_en.properties
> OP-564 change shortcut key to be unique

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
> OP-565 increase width of preferred size for date/time

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
- src/main/java/org/isf/utils/jobjects/JTextFieldSearchModel.java
- src/main/java/org/isf/utils/jobjects/OhTableModel.java
See OP-566
One minor change in the resource bundle for the title line and added ".toUpperCase()" for table column names.  No real code changes.
> OP-566 update dialog style to match

- bundle/language_en.properties
> OP-567 make shortcut key unique

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
> OP-568 use correct resource key for end of range

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/utils/jobjects/JFromDateToDateChooser.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
See OP-561
Attempted to make the least change yet make the dialog look better.
> OP-561 Improve StockCard dialog; add title and space

- bundle/language_en.properties
> OP-570 make shortcut key unique

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
> OP-573 make buttons use same style

- bundle/language_en.properties
> OP-574 make shortcut key unique in Therapy dialog

- bundle/language_en.properties
- src/main/java/org/isf/stat/gui/DiseasesListLauncher.java
> OP-575 make Exams and Disease report dialogs consistent

- src/main/java/org/isf/menu/gui/UserGroupBrowsing.java
> OP-578 Fix ordering of Edit and New buttons

- src/main/java/org/isf/lab/gui/LabEditExtended.java
> OP-580: fix formatting on Edit Lab Exam window

- src/main/java/org/isf/lab/gui/LabEdit.java
> OP-581: fix formatting on Edit Lab Exam window

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-577 Fix date comparation for payments

- src/main/java/org/isf/lab/gui/ExamPicker.java
- src/main/java/org/isf/lab/gui/LabNew.java
See OP-583
Did a little formatting updating too.
> OP-583 Fix up Exams List window

- src/main/java/org/isf/utils/jobjects/JTextFieldSearchModel.java
> OP-587 update windows to match standards

- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
See OP-588; move Cancel button to the end of the row.
> OP-588 make button order match standards

- src/main/java/org/isf/medicals/gui/MedicalEdit.java
See OP-589 for visual changes.
Also cleaned the code up a little.
> OP-589 Pharmacy->New/Edit dialog improvements

- src/main/java/org/isf/lab/gui/LabNew.java
See OP-590 for visual change.
Also cleaned the code up a little; had to do some reformatting unfortunately.
> OP-590 fix text truncation

- bundle/language_en.properties
- bundle/language_it.properties
- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-591 disclose accounting admin features

- src/main/java/org/isf/video/gui/PhotoboothComponentImpl.java
`instanceOf` returns false if the object is null so there is no need to check for it
> Chore: instanceOf handles the null; if null then false

- src/main/java/org/isf/supplier/gui/SupplierEdit.java
> OP-596: Update New Supplier window

- bundle/language_en.properties
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
> OP-595 new button names/order

- src/main/java/org/isf/exa/gui/ExamEdit.java
> OP-602 Settings->Exams->New/Edit dialog improvements

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-594 Fix BillManager layout in singleuser mode

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-597 Fix user selection upon new bill or new payment

- src/main/java/org/isf/operation/gui/OperationEdit.java
Made other minor code changes; the diff looks worse then the actual changes.
> OP-605 Settings->Operation->New/Edit dialog improvements

- src/main/java/org/isf/vaccine/gui/VaccineEdit.java
Misc. code improvements and a little reformatting.
> OP-604 Settings->Vaccine->New/Edit dialog improvements

- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowserEdit.java
See OP-610
Fixed up dialog sizing and made other code/format improvements.
> OP-610 Settings->Types->Admission Type and New/Edit

- src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowserEdit.java
See OP-611
Code improvements including removing unneeded code and additional formatting.
> OP-611 Settings->Types->Discharge Type and New/Edit

- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
See OP-599.
(build failing because it needs https://github.com/informatici/openhospital-core/pull/460)
Cc: @claudiorosazza
> OP-599 extend pex note field

- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowserEdit.java
See OP-612
Some code cleanup and formatting too.
> OP-612 Settings->Types->Delivery Type and New/Edit

- src/main/java/org/isf/priceslist/gui/ListBrowser.java
- src/main/java/org/isf/priceslist/gui/ListEdit.java
See OP-609
Includes some code and formatting improvements.
> OP-609 Settings->Price List->Manage Lists->New/Edit dialog

- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowserEdit.java
See OP-613
Changes include code improvements and formatting.
> OP-613 Settings->Types->Delivery Result Type and New/Edit

- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowserEdit.java
See OP-615.
Like the other PRs; code and formatting too.
> OP-615 Settings->Types->Disease Type and New/Edit

- src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowser.java
- src/main/java/org/isf/medstockmovtype/gui/MedicaldsrstockmovTypeBrowserEdit.java
See OP-616
Includes code and formatting improvements.
> OP-616 Settings->Types->Medical Stock Mov Type and New/Edit

- src/main/java/org/isf/opetype/gui/OperationTypeBrowser.java
- src/main/java/org/isf/opetype/gui/OperationTypeEdit.java
See OP-618.
Includes code and formatting improvements.
> OP-618 Settings->Types->Operation Type and New/Edit

- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeEdit.java
See OP-619.
Includes code and formatting improvements.
> OP-619 Settings->Types->Pregnant Treatment Type and New/Edit

- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
See OP-614
Code improvements and formatting.
> OP-614 Settings->Types->Exam Type and New/Edit

- src/main/java/org/isf/medtype/gui/MedicalTypeBrowser.java
- src/main/java/org/isf/medtype/gui/MedicalTypeBrowserEdit.java
See OP-617.
Code and formatting improvements too.
> OP-617 Settings->Types->Medicals Type and New/Edit

- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
- src/main/java/org/isf/vactype/gui/VaccineTypeEdit.java
See OP-620
Usual code and formatting improvements.
> OP-620 Settings->Types->Vaccine Type and New/Edit

- src/main/java/org/isf/pricesothers/gui/PricesOthersBrowser.java
- src/main/java/org/isf/pricesothers/gui/PricesOthersEdit.java
> OP-621 Settings->Types->Other Prices and New/Edit

- src/main/java/org/isf/dicomtype/gui/DicomTypeEdit.java
See OP-623
Usual code cleanup and formatting
> OP-623 Settings->Types-> DICOM -> New/Edit

- bundle/language_en.properties
It appears that this property isn't really being used but if it is, correct the spelling.
> Chore: fix spelling

- bundle/language_en.properties
See OP-504 comments; change 'Patient Vaccines' to 'Vaccines' in main menu
> OP-504 change 'Patient Vaccines' to 'Vaccines' in main menu

- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
> OP-626_close-button-in-patient-examination

- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
- src/main/java/org/isf/exa/gui/ExamEdit.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
Started out just formatting some very ugly looking code.   Also add a few missing braces, some missing annotations, etc.  All minor cleanups.
> Chore: formatting and small changes

- src/main/java/org/isf/dicom/gui/ShowPreLoadDialog.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/menu/gui/SplashWindow3.java
- src/main/java/org/isf/operation/gui/OperationBrowser.java
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/priceslist/gui/PricesBrowser.java
- src/main/java/org/isf/sms/gui/SmsBrowser.java
- src/main/java/org/isf/sms/gui/SmsEdit.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/supplier/gui/SupplierBrowser.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
- src/main/java/org/isf/video/PhotoboothTester.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
- src/main/java/org/isf/video/gui/PhotoboothComponentImpl.java
> Chore: anonymous classes replaced with lambda expressions

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
- src/main/java/org/isf/video/gui/PatientPhotoPanel.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
Move duplicate code in both branches of `if` out of the conditional.
A little formatting ended up in the PR too.
> Chore: remove duplicate code in both branches of if

- src/main/java/org/isf/visits/gui/InsertVisit.java
- src/main/java/org/isf/visits/gui/VisitView.java
> Chore: remove what looks like an octal value for int array

- bundle/language_en.properties
- src/main/java/org/isf/opd/gui/OpdBrowser.java
> OP-658 add patient name to delete message

- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
> OP-659 fix New/Edit/Delete buttons

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
See this Core [PR](https://github.com/informatici/openhospital-core/pull/495) for the changes that motivated the changes in the GUI repo.    The biggest Core change was the removal of unneeded `throws OHServiceException` clauses in the `accounting` and `admission` packages. 
The code compiles cleanly locally when paired with the Core changes.
> Chore: changes required because of Core PR #495

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/visits/gui/InsertVisit.java
> OP-700 Fixing validation error (null ward means ODP)

- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowBase.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
See OP-699
Did the refactoring on top of the hotfix track
> OP-699 refactoring for duplicated code

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
> OP-712 persist and show maternity visit date

- src/main/java/org/isf/visits/gui/InsertVisit.java
> OP-714: only list appropriate wards (hotfix)

- src/main/java/org/isf/visits/gui/InsertVisit.java
See OP-714
Used similar code to that found in `AdmissionBrowswer.java` in `getWardPanel()` method.
> OP-714: only list appropriate wards

- pom.xml
- src/test/java/org/isf/admission/gui/ward/WardComboBoxInitializerTest.java
This PR takes care of updating the dependencies noted in PR-1012, PR-1013, PR-1046, and PR-1057.
The updates in PR-813, PR-814, and PR-1011 have already been done in the Java8 PR committed yesterday.
The build was clean and all the tests passed (after a tweak to a test file).
> Chore: Update dependencies to latest versions

- oh.bat
- oh.ps1
- oh.sh
- rsc/dicom.properties.dist
- Added option for setting DICOM storage type
- Some final fixes for 1.11.1
> Dicom updates

- pom.xml
I will rebase dependabot PRs after this is committed
> Chore: update pom.xml based on dependabot PRs

- src/main/java/org/isf/visits/gui/InsertVisit.java
> OP-728: quick fix for NPE

- pom.xml
I will rebase the dependabot PR after this is comitted.
> Chore: update pom.xml based on dependabot PR

- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/visits/gui/InsertVisit.java
> Chore: replace explicit types with <>

- src/main/java/org/isf/visits/gui/VisitView.java
> OP-736 fix class cast exception when trying to remove a visit in the Worksheet

- pom.xml
See OP-332 and [Core PR-560](https://github.com/informatici/openhospital-core/pull/560
)
> OP-332 consolidate JasperReports dependency in Core

- pom.xml
Per dependbot; will rebase after this is committed.
> Chore: update maven-jar-plugin to 3.2.1

- pom.xml
I will rebase once this is committed.
> Chore: plugin updates per dependabot

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-745 assign to correct variable

- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
See OP-747, remove message no longer used.
Companion to CORE PR https://github.com/informatici/openhospital-core/pull/582
> OP-747 remove unused msg given CORE changes

- bundle/language_en.properties
- src/main/java/org/isf/stat/gui/report/DiseasesList.java
- src/main/java/org/isf/stat/gui/report/DisplayReport.java
- src/main/java/org/isf/stat/gui/report/ExamsList1.java
- src/main/java/org/isf/stat/gui/report/GenericReportAdmission.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/stat/gui/report/GenericReportDischarge.java
- src/main/java/org/isf/stat/gui/report/GenericReportExamination.java
- src/main/java/org/isf/stat/gui/report/GenericReportFromDateToDate.java
- src/main/java/org/isf/stat/gui/report/GenericReportMY.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatient.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatientVersion2.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalOrder.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStock.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockCard.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockWard.java
- src/main/java/org/isf/stat/gui/report/GenericReportUserInDate.java
- src/main/java/org/isf/stat/gui/report/WardVisitsReport.java
> OP-758 check for no pages in generated report

- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/utils/jobjects/VoDateTextField.java
See OP-751
Companion to CORE PR https://github.com/informatici/openhospital-core/pull/586
> OP-751 fix date pattern

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
- src/main/java/org/isf/medstockmovtype/gui/MedicalsrMovPatList.java
See OP-759
BTW, I fixed the order of the buttons in the Launch Report dialog to match the image in the JIRA issue.
> OP-759: double click to launch report dialog

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
> OP-775 return the date

- src/main/java/org/isf/opd/gui/OpdBrowser.java
> OP-776 off by 1 on the month conversion

- src/main/java/org/isf/operation/gui/OperationRowBase.java
> OP-748 Use abstract method instead of concrete method

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
See [OP-774](https://openhospital.atlassian.net/browse/OP-774).
Paired with https://github.com/informatici/openhospital-core/pull/609.
Will follow [OP-781](https://openhospital.atlassian.net/browse/OP-781) after v1.11.3
> Laboratory honoring date AND time now

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-785 fix "OPD No" field prediction

- src/main/java/org/isf/stat/gui/DiseasesListLauncher.java
- src/main/java/org/isf/stat/gui/ExamsList1Launcher.java
- src/main/java/org/isf/stat/gui/report/DiseasesList.java
- src/main/java/org/isf/stat/gui/report/ExamsList1.java
- src/main/java/org/isf/stat/gui/report/GenericReportAdmission.java
- src/main/java/org/isf/stat/gui/report/GenericReportBill.java
- src/main/java/org/isf/stat/gui/report/GenericReportDischarge.java
- src/main/java/org/isf/stat/gui/report/GenericReportExamination.java
- src/main/java/org/isf/stat/gui/report/GenericReportFromDateToDate.java
- src/main/java/org/isf/stat/gui/report/GenericReportMY.java
- src/main/java/org/isf/stat/gui/report/GenericReportOpd.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatient.java
- src/main/java/org/isf/stat/gui/report/GenericReportPatientVersion2.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalOrder.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStock.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockCard.java
- src/main/java/org/isf/stat/gui/report/GenericReportPharmaceuticalStockWard.java
- src/main/java/org/isf/stat/gui/report/GenericReportUserInDate.java
- src/main/java/org/isf/stat/gui/report/WardVisitsReport.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
Started reviewing report code and found issues involving code cleanup
- Remove unused imports
- Make variables local instead of class
- Remove GregorianCalendar usage
- General code cleanup
- etc.
> Chore: Cleanup of stat package

- oh.bat
- oh.ps1
- oh.sh
- Various fixes and updates for CLIENT mode
- Better error checking
- Updated zulu JAVA JRE version
- Updated MariaDB version
- Needs testing
Signed-off-by: @mizzioisf
> Updates for 1.11.3

- rpt/MOH717_Monthly_Workload_Report_for_Hospitals_page2b.jrxml
See OP-826  misspelled paramete
> OP-826 fix parameter name

- pom.xml
Combine and test recent dependabot suggested upgrades as a single unit. This fixes a RCE CVE in Spring too.
This brings GUI repo in line with CORE repo once the corresponding [PR](https://github.com/informatici/openhospital-core/pull/642) there is committed. 
I will update all the individual PRs once this is committed.
> Chore: update all jars in single POM to test

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
See [OP-761](https://openhospital.atlassian.net/browse/OP-761). (not tested yet)
> OP-761 Drop field OPD_DATE_VIS

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
> OP-852 Update dateTo and dateFrom for Pharmacy -> Pharmaceutical Stock

- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooser.java
> OP-857 new date/time chooser widget

- pom.xml
This is test all the changes together and makes the jars in this repo match those in Core after this PR: https://github.com/informatici/openhospital-core/pull/656
I will close the corresponding dependabot PRs after this PR is merged.
> Chore: combine all recent dependabot updates

- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-860 update OPD dialogs

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
Time was added by mistake in previous push.
> OP-866 remove time from Lot Information dialog

- src/main/java/org/isf/patient/gui/PatientInsert.java
> OP-870 correct dialog title

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-873 correct time value

- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/utils/Constants.java
- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooser.java
See OP-876
Note: I have a large number of changes queued up in my playpen for the new date and date/time widget.   I am attempting to break them into smaller units so it is easier to see the changes.    All my other changes are dependent on this PR being merged.
Thanks.
> OP-876 Admission/Patient → Examination date/time widget change

- src/main/java/org/isf/operation/gui/OperationRowAdm.java
- src/main/java/org/isf/operation/gui/OperationRowBase.java
- src/main/java/org/isf/operation/gui/OperationRowEdit.java
- src/main/java/org/isf/operation/gui/OperationRowOpd.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
> OP-883 update date/time on Operation panel

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
> OP-880 Delivery panel changes for date/time pickers

- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
> OP-881 Update date picker for New/Edit Patient (extended)

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-882 Update date/time pickers for New/Edit OPD Registration

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
> OP-904 Change date chooser on Pharmacy->Pharmaceuticals Stock Ward

- pom.xml
- src/main/java/org/isf/accounting/gui/totals/UserTotal.java
- src/main/java/org/isf/lab/gui/elements/ExamRowSubPanel.java
- src/test/java/org/isf/lab/gui/elements/ExamRowSubPanelTest.java
- src/test/java/org/isf/lab/gui/elements/PatientComboBoxTest.java
- src/test/resources/language_en.properties
- src/test/resources/log4j.properties
See OP-906.
Note: fixed also some tests settings
> OP-906 Fix GUI Tests with Spring 5 and Junit 5 (jupiter)

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
> OP-908 Fix bad resolution of code merge after 1.11.3

- src/main/java/org/isf/admission/gui/PatientFolderReportModal.java
> OP-907 Change date choosers on Admission/Patient->Clinical Sheet->Launch Report

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/hospital/gui/HospitalBrowser.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooser.java
- src/main/java/org/isf/utils/jobjects/GoodTimeChooser.java
See OP-820
Settings -> Hospital
This depends on the Core PR: https://github.com/informatici/openhospital-core/pull/678
I simplified the layout code for the Hospital Browser window in the process.
> OP-820 add hospital level visit start/end time to browser

- bundle/language_en.properties
- src/main/java/org/isf/hospital/gui/HospitalBrowser.java
> OP-820 add hospital level visit duration to Hospital browser

- pom.xml
This syncs up with the corresponding jar changes in Core
I will rebase the dependabot PRs after this is merged.
> Chore combine all recent dependabot updates into single unit to test

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-915 fix "to" year when using year selection widget

- src/main/java/org/isf/lab/gui/LabEdit.java
See OP-912
Also made some small code improvements found by SonarLint and Intellij Analyze
> OP-912 Change date/time widget in Lab->New/Edit when LABEXTENDED and LABMULTIPLEINSERT are no

- src/main/java/org/isf/lab/gui/LabEditExtended.java
See OP-913
Also made some small code improvements found by SonarLint and Intellij Analyze
> OP-913 Change date/time widget in Lab->New/Edit when LABEXTENDED is yes and MULTIPLEINSERT is no

- src/main/java/org/isf/lab/gui/LabNew.java
See OP-914
Other small changes made after running SonarLint and IntelliJ Analyze
> OP-914 Change date/time widget in Lab->New when LABEXTENDED and LABMULTIPLEINSERT are yes

- src/main/java/org/isf/operation/gui/OperationRowBase.java
The current operation drop down list has been integrated with a filter
component (textbox + search button)
See OP-704.
> OP-704 Add search box for Operations in OPD and Admission tabs

- src/main/java/org/isf/opd/gui/OpdBrowser.java
> OP-905 center OPD browser window

- src/main/java/org/isf/operation/gui/OperationRowBase.java
with changes looks like:
BTW, this is why I hate GridBagLayout
> OP-704 change column spacing to stop truncation

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
Stumbled upon this file and using SonarLint and IntelliJ Analyzer made various code improvements.   This is similar to the work done in OP-445.
> Chore: code cleanup

- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEntryForm.java
See OP-918 Change date chooser for Admission/Patient->Therapy->Add Therapy
Also made minor changes based on SonarLint and IntelliJ's Analyze tool
> OP-918 update Date chooser widget

- src/main/java/org/isf/visits/gui/VisitView.java
> OP-919 fix size of worksheet window

- pom.xml
- src/main/java/org/isf/utils/time/Converters.java
> OP-921 remove unused conversion routines and JODA package from pom.xml

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
> OP-922 fix dateformat exceptions in report generation

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-923 fix dateformat exceptions in report generation

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-924 update year formatting

- src/main/java/org/isf/utils/jobjects/OhTableDrugsModel.java
> OP-926 fix DataTimeParseException

- rsc/ipinfo.properties
- rsc/ipinfo.properties.dist
- rsc/ipinfo2.properties.dist
- src/main/java/org/isf/telemetry/gui/TelemetryGUI.java
- merged develop
- changed FreeGeoIPJSON -> GeoIpLookup service
> Op 312 - telemetry module

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
> OP-930 use new Date chooser

- src/main/java/org/isf/menu/gui/MainMenu.java
> OP-931 If  SMSENABLED=no then remove SMS Manager from Settings menu

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
See OP-933 for how to recreate
> OP-933 Change date chooser for Pharmacy->Pharmaceuticals->Stock->Report, etc.

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-940 do not change the date when editing OPD entry

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-941 do not allow changed OPD No.

- pom.xml
Combine all recent dependabot jar updates to test together.  Should be merged after the corresponding [Core PR 715](https://github.com/informatici/openhospital-core/pull/715) is merged.
> Chore: combine all recent dependabot jar updates to test together

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicals/gui/MedicalEdit.java
See OP-942
Note: having a hard time testing this in my current environment.
> OP-942 fix locking exception

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
See OP-947
This is the hotfix version.
This PR is dependent on this PR https://github.com/informatici/openhospital-core/pull/719 in the Core project.
> OP-947 do not export the button object to Excel file

- bundle/language_en.properties
- src/main/java/org/isf/visits/gui/InsertVisit.java
See OP-939
Requires PR in CORE: https://github.com/informatici/openhospital-core/pull/720
> OP-939 show all wards; move validation to core; set dialog title

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
See OP-944
Did some other file cleanup based on SonarLint and IntelliJ Analyze tools
> OP-944 Change date choosers for Lot Information

- src/main/java/org/isf/operation/gui/OperationRowBase.java
Fix bug when searching for an intervention (changed the size of
components based on the length of the interventions) (See OP-704)
> OP-704-FIX:

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
See OP-943
This requires CORE PR https://github.com/informatici/openhospital-core/pull/723 to be merged to compile cleanly
> OP-943 honor the Excel file extension and use matching exporting code

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
> OP-950 set initial from/to dates with correct time component

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
See OP-949
I don't like the fix but it works.    Depending on whether or not the drug has any stock and/or whether the actual number is changed most of the time the value is a DOUBLE but in some paths it is an INTEGER.  The "fix" is to handle both cases.
If this is acceptable then I will create the hotfix PR.
> OP-949 fix classcastexception during Recity

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
See OP-949
While creating the hotfix version I noticed that I forgot to rename two other fields/metho names in the original PR; sorry
> OP-949 missed two renames

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
This is the hotfix version 
See OP-953
> OP-953 fix column headers

- src/main/java/org/isf/therapy/gui/TherapyEdit.java
> OP-954 update month and year choosers

- src/main/java/org/isf/dicom/gui/ShowPreLoadDialog.java
- src/main/java/org/isf/utils/time/Converters.java
> OP-958 remove CustomJDateChooser widget

- pom.xml
Will rebase dependabot PRs when this is committed.
Was tested with `mvn clean test` with the updated jar from https://github.com/informatici/openhospital-core/pull/734
> Chore: combine all recent dependabot jar updates

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
See OP-963
This is the hotfix version of the change.
> OP-963 fix height/weight text

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
See OP-956.
This should supersed https://github.com/dbmalkovsky/openhospital-gui/tree/OP-956.
Cc: @dbmalkovsky
> OP-956 Fix OPD edit from Admission-Data-OPD-EDIT

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
> Link listeners for data changed/updated

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
See OP-957
Sorry for all the space changes; it happened copying the file back and forth while making other changes.
> OP-957 remove CustomJDateChooser

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/utils/Constants.java
> OP-966 remove seconds in dialogs and windows

- pom.xml
Around round of updates tested together. All tests clean in IDE and `mvn clean test`.
> Chore: combine 6 recent dependabot updates into single PR for testing

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
See [OP-844](https://openhospital.atlassian.net/browse/OP-844)
Note: the accelerator key had to change because of conflicts.   
Note: the button name will change to Image when [OP-846](https://openhospital.atlassian.net/browse/OP-846) is done.
> OP-844 add DICOM button in Admission/Patient Browser

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/operation/gui/OperationRowBase.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/sms/gui/SmsEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEntryForm.java
- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooserBase.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
- src/main/java/org/isf/visits/gui/VisitView.java
- src/test/java/org/isf/admission/gui/ward/WardComboBoxInitializerTest.java
> OP-968 use TimeTools.getNow()

- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
> OP-845 Add Laboratory button in Admission/Patient browser

- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooserBase.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
> OP-971 use TimeTools.truncateToSeconds() because it has a null check

- src/main/java/org/isf/utils/jobjects/GoodDateChooser.java
See OP-971
found during interactive testing
> OP-971 revert overzealous use of truncateToSeconds() method

- pom.xml
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
See OP-969 
Uses `com.twelvemonkeys.imageio` module to get the code to compile with JDK 11
> OP-969 replace JPEGImageReader

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
See OP-975
Interactive testing looks good.
Companion CORE PR: https://github.com/informatici/openhospital-core/pull/779
> OP-975: use @Autowire

- rpt/OH010_OutPatientReport_es.properties
- rpt/OH010_OutPatientReport_fr.properties
- rpt/OH010_OutPatientReport_it.properties
- rpt/OH010_OutPatientReport_sv_SE.properties
Merge new 100% transaltions from Transifex.
> Transifex merge

- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
> OP-984 correct switching back to ALL in Diseases Browser

- src/main/java/org/isf/exa/gui/ExamBrowser.java
See OP-983
Made a few more changes to better match other settings browser's code
> OP-983 remove the problematic sorting code

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
See OP-986 which includes how to reproduce the issue
> OP-986 fix getting Ward column when other wards present

- .github/workflows/maven.yml
- pom.xml
> OP-854 Move to JDK 11 - gui

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/supplier/gui/SupplierBrowser.java
- src/main/java/org/isf/supplier/gui/SupplierEdit.java
See OP-780.
Paired with https://github.com/informatici/openhospital-core/pull/767.
>  OP-780 - OH GUI make spring use xxx ACT (rebased) 

- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/elements/ExamRowSubPanel.java
> OP-989 improve LabEdit and LabEditExtended gui

- pom.xml
I will rebase other PRs once this is merged.
> Chore: combine all 3 recent dependabot jar updates to match changes in Core

- pom.xml
- src/test/java/org/isf/utils/image/ImageUtilTest.java
> OP-998 remove definition of spring-cloud-starter-openfeign

- pom.xml
Ran `mvn clean test` without issue
Will rebase the dependabot PR once this is merged.
> Chore: combine all recent dependabot jar updates to match changes in Core

- bundle/language_en.properties
- pom.xml
- rsc/version.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/utils/jobjects/DateTextField.java
Contains:
- OP-1001
- OP-1002
Note: check are failing because it needs https://github.com/informatici/openhospital-core/tree/v1.11.4.
> Hotfix for 1.11.4

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1002 [OH GUI] Add "createdBy" column in MovStockBrowser

- bundle/language_en.properties
> OP-979 Change "New Admittance" for OPD into "New Attendance"

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
> OP-1004 MedicalStockMov Charge movement has no time field

- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
> OP-1006 fix off by one for month selected index

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-1007 set Ward combobox if single OPD ward

- src/main/java/org/isf/accounting/gui/BillBrowser.java
> OP-696 Use selected patient; filter list by double clicking

- oh.bat
- oh.ps1
- oh.sh
Batch of updates for the incoming 1.12 release.
Last update: clarified database server console messages
Update: added check for SERVER feature
New features:
- Full 64bit support on Windows, also for DICOM ! (no more ugly DICOM workarounds - see https://openhospital.atlassian.net/browse/OP-706)
- SERVER mode support (for portable installations) -> give it a try !
- Arabic Language support - oh.sh -l ar
- JRE 11 !
- MariaDB 10.6.x !
Along with the usual bug fixes, cosmetic/syntax changes, etc.
> OP-347 Cumulative script update for 1.12

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-1012 Fixes for saving edited OPD record

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
> OP-1008 Clarify New Attendance and Re-Attendance fields

- src/main/java/org/isf/menu/gui/MainMenu.java
> OP-1010 When SINGLEUSER=yes the LOGOUT button exits the application

- bundle/language_en.properties
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/utils/jobjects/GoodDateTimeChooserBase.java
See OP-1013
Note there is no need to check the ward with the patient's sex as the combobox is only populated with matching wards.
> OP-1013 Improve the OPD Next Visit workflow

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/sms/gui/SmsBrowser.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/utils/jobjects/GoodFromDateToDateChooser.java
- src/main/java/org/isf/utils/jobjects/StockCardDialog.java
- src/main/java/org/isf/utils/jobjects/StockLedgerDialog.java
See OP-274
Also did some cleanup of one file with results of IntelliJ Analyze command.
There is a corresponding documentation PR to follow.
> OP-274 use common date from/date to label properties

- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
> OP-687 Fix waiting cursors upon patient search

- bundle/language_en.properties
- src/main/java/org/isf/help/HelpViewer.java
See OP-684
Added a Yes/No dialog message if the doc file is not found locally.
> OP-684 Provide option to Launch online version of doc if not found locally

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
> OP-1023 Fix NPE by using the correct variable name

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
See OP-1009.
Changed one bundle.
> OP-1009 To complete [Accounting] doc

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/accounting/gui/BillDataLoader.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/test/java/org/isf/accounting/gui/BillDataLoaderTest.java
> OP-576 - filter bill manager table upon cashier

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
See OP-527.
Paired with https://github.com/informatici/openhospital-core/pull/865.
> OP-527 inconsistent column definition for XXX_DELETED fields

- rpt_stat/BillsReportMonthlyWard_subreport.properties
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
Reports without jTitle property are not listed (e.g. subreports)
> OP-999: Hide subreports from list

- bundle/language_ar.properties
- bundle/language_ar_SA.properties
- bundle/language_en.properties
- bundle/language_es.properties
- bundle/language_fr.properties
- bundle/language_it.properties
- bundle/language_zh_CN.properties
- src/main/java/org/isf/opd/gui/OpdBrowser.java
See OP-213.
Add also USER column and related filter (like in Wolisso's project).
Paired with https://github.com/informatici/openhospital-core/pull/863.
> OP-213 add search field for opd records

- bundle/language_en.properties
> OP-1027 set Duration column header property in Ward Browser.

- bundle/language_en.properties
> OP-1026 add missing anamnesis related property strings

- src/main/java/org/isf/menu/gui/MainMenu.java
> OP-1031 fix NPE; when canceling login there is no session id

- oh.bat
- oh.ps1
- oh.sh
- rsc/settings.properties.dist
Fix and updates for DEMO data usage.
It should be now possible to switch form DEMO data and normal portable data seamlessy
> Demo data usage script updates

- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
See OP-1044
I am not proud of the fix but as this is how it was done in the original import of the code I just leveraged it instead of having to rewrite the whole layout of the dialog.
> OP-1044 fix menu size

- .gitignore
- rsc/resolutions.xml
- Removed resolutions.xml file
- Updated .gitignore
> File cleanup

- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
> OP-466: Explicit type can be replaced with <>

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/admission/gui/ward/WardComboBoxInitializer.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
- src/main/java/org/isf/operation/gui/OperationRowBase.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/utils/jobjects/OhTableModel.java
- src/main/java/org/isf/utils/jobjects/OhTableModelExam.java
- src/main/java/org/isf/utils/jobjects/OhTableOperationModel.java
- src/main/java/org/isf/utils/jobjects/VoDoubleTextField.java
- src/main/java/org/isf/utils/jobjects/VoFloatTextField.java
- src/main/java/org/isf/utils/jobjects/VoIntegerTextField.java
> OP-1052: Use String.valueOf() instead of empty string concatenation

- oh.bat
- oh.ps1
- oh.sh
New batch of script updates, should be ready for 1.12.1.
- More "interactive": get back to menu instead of exiting where possible
- Better and safer clean options (it is possible to select what to delete)
- Added direct database settings reading from database.properties file
- Updates and fixes
- Show OH version in main menu
_needs_testing_ !
> OP-1032 Script updates for 1.12.1

- bundle/language_en.properties
related to https://github.com/informatici/openhospital-core/pull/910
> OH-722 Validate that a visit does not overlap other visits

- bundle/language_en.properties
- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
> OP-990 Add further check for underlying data changes in billing

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
See OP-1059.
Paired with https://github.com/informatici/openhospital-core/pull/924.
> OP-1059 Fix Admission Diagnosis IN (cannot be null)

- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
See OH2-183.
Although the new `LaboratoryStatus` is not yet managed in the GUI, the field has to be consistent with the UI workflow: laboratory inserted with result (the only possibility in GUI) -> status: `DONE("done")`
> OH2-183 Add LaboratoryStatus management

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
Chore: remove `if (true)` test
> Chore: remove `if (true)` test

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> Chore: simplify date comparisons

- src/main/java/org/isf/dicom/gui/DicomViewGui.java
Paired PR for OP-717.
Fixed compilation errors in GUI component.
> OP-717 DICOM BLOB in a separate table

- oh.ps1
- oh.sh
-> corrected a bug on DEMO mode
-> code cleanup
-> code alignment with oh-api scripts - see https://github.com/informatici/openhospital/pull/200
> OP-1033 Script fix and updates

- src/main/java/org/isf/admission/gui/validation/OperationRowValidator.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
> OP-1066 new OHExceptionMessage() constructor

- pom.xml
This matches changes in Core.
I will rebase the individual dependabot PRs after this is merged.  Thanks.
> Chore: combine recent dependabot jar updates to match changes in Core

- bundle/language_en.properties
- src/main/java/org/isf/menu/gui/UserBrowsing.java
- src/main/java/org/isf/menu/gui/UserEdit.java
> OP-894 use value of zero to turn off password length checking

- src/main/java/org/isf/menu/gui/Login.java
> OP-897 use value of zero to turn off password retries checking

- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
- src/main/java/org/isf/utils/jobjects/JLabelRequired.java
- src/main/java/org/isf/utils/jobjects/JMonthChooser.java
- src/main/java/org/isf/utils/jobjects/VoDoubleTextField.java
- src/main/java/org/isf/utils/jobjects/VoFloatTextField.java
- src/main/java/org/isf/utils/jobjects/VoIntegerTextField.java
Found with Intellij Analyze and DocLint
> Chore: JavaDoc improvements

- bundle/language_en.properties
- pom.xml
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
See OP-1035.
Paired with https://github.com/informatici/openhospital-core/pull/905.
> OP-1035 - Patient Consensus Management

- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
See OP-1086
Using the update Core jar; rebuilt project cleanly
Dependent on https://github.com/informatici/openhospital-core/pull/978
> OP-1086: removed deprecated methods from org.isf.lab.model.Laboratory

- bundle/language_en.properties
- src/main/java/org/isf/menu/gui/UserBrowsing.java
- src/main/java/org/isf/menu/gui/UserEdit.java
See OP-1072
Requires:  https://github.com/informatici/openhospital-core/pull/993
If this is OK, I will update the doc
> OP-1072: provide way to unlock user's account

- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/lab/gui/LabNew.java
See OH2-201.
This PR is to fix a previous change for OH2-183.
> OH2-201 add the request exam cancellation feature invalid state

- oh.bat
- oh.ps1
- oh.sh
Fixes:
https://openhospital.atlassian.net/browse/OP-1102
https://openhospital.atlassian.net/browse/OP-1105
Also contains version MariaDB version updates, see https://github.com/informatici/openhospital/pull/204
> OP-1102 OP-1105 Latest script fixes and updates

- src/main/java/org/isf/menu/gui/MainMenu.java
> OP-1101 Main Menu title set to "OH"

- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
See OP-1097.
Once merged, I will update the doc, if needed (I think we can overllok small things like this one)
Now
Before
> Fix Patient Registration window's size after Patient Consensus

- oh.ps1
- oh.sh
See https://openhospital.atlassian.net/browse/OP-1114
> OP-1114 API server workaround in scripts

- pom.xml
Upgrade Spring Framework and Spring Boot
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.13
> Chore: Upgrade Spring

- src/main/java/org/isf/accounting/gui/PatientBillEdit.java
also fix current admission check
> OP-1116 Fix currency code check

- pom.xml
Matches change in Core:  https://github.com/informatici/openhospital-core/pull/1037
> Chore: Upgrade Spring 5.3.29

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/dicom/gui/DicomLoader.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
- src/main/java/org/isf/dicom/gui/ThumbnailViewGui.java
- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
- src/main/java/org/isf/medicals/gui/MedicalEdit.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/sms/gui/SmsEdit.java
- src/main/java/org/isf/therapy/gui/TherapyEdit.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
- src/main/java/org/isf/utils/jobjects/VoDoubleTextField.java
- src/main/java/org/isf/utils/jobjects/VoFloatTextField.java
- src/main/java/org/isf/utils/jobjects/VoIntegerTextField.java
- src/main/java/org/isf/visits/gui/InsertVisit.java
- src/main/java/org/isf/visits/gui/VisitView.java
- src/main/java/org/isf/xmpp/gui/ChatMessages.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
There is a small performance improvement
> Chore: replace single char string literal in concatentation with character literal

- pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.15
Matches similar update in Core
> Upgrade to Spring Boot 2.7.15

- src/main/java/org/isf/utils/treetable/AbstractTreeTableModel.java
- src/main/java/org/isf/utils/treetable/JTreeTable.java
- src/main/java/org/isf/utils/treetable/TreeTableCellRenderer.java
- src/main/java/org/isf/utils/treetable/TreeTableModel.java
- src/main/java/org/isf/utils/treetable/TreeTableModelAdapter.java
See OP-1123
When this PR is committed I will submit the matching version for Core deleting the package.
The changes in Core and GUI have been tested successfully locally.
> OP-1123: Move org.isf.utils.treetable package to GUI

- src/main/java/org/isf/utils/table/TableMap.java
- src/main/java/org/isf/utils/table/TableSorter.java
See OP-1125
When this PR is committed I will submit the matching version for Core deleting the package.
The changes in Core and GUI have been tested successfully locally.
> OP-1125: Move org.isf.utils.table package to GUI

- pom.xml
Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.30
Matches change in Core: https://github.com/informatici/openhospital-core/pull/1095
> Upgrade to Spring Framework 5.3.30

- bundle/language_en.properties
- src/main/java/org/isf/visits/gui/InsertVisit.java
> OP-1128: validate date

- src/main/java/org/isf/accounting/gui/BillBrowser.java
- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/medicals/gui/MedicalEdit.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/menu/gui/MainMenu.java
- src/main/java/org/isf/menu/gui/UserEdit.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/operation/gui/OperationBrowser.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
- src/main/java/org/isf/xmpp/gui/CommunicationFrame.java
Examples include removing assignments that are the default value, the variable is replaced with another value, or the variable is never used again.
> Chore: remove unused assignments

- pom.xml
Release notes; https://github.com/spring-projects/spring-boot/releases/tag/v2.7.16
There is a corresponding change in the CORE repo.
> Upgrade to Spring Boot 2.7.16

- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowserEdit.java
> OP-1135 reset description field when editing Admission Type object

- bundle/language_en.properties
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
See OP-1130
Matching changes for Core PR: https://github.com/informatici/openhospital-core/pull/1104
> OP-1130 improve JPA methods - admission package

- bundle/language_en.properties
- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowserEdit.java
See OP-1130
Changes for the admtype package.
Matching changes for CORE PR: https://github.com/informatici/openhospital-core/pull/1105
> OP-1130 improve JPA methods- admtype package

- src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeEdit.java
See OP-1130
dicomtype package updates to match Core PR: https://github.com/informatici/openhospital-core/pull/1108
> OP-1130 improve JPA methods - dicomtype package

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowser.java
- src/main/java/org/isf/admtype/gui/AdmissionTypeBrowserEdit.java
- src/main/java/org/isf/agetype/gui/AgeTypeBrowser.java
- src/main/java/org/isf/anamnesis/gui/PatientHistoryEdit.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeBrowser.java
- src/main/java/org/isf/dicomtype/gui/DicomTypeEdit.java
There are about 400 more of this type of change but before I do them all I thought I'd start small to see the reaction.
> Chore: remove unnecessary `this`

- src/main/java/org/isf/disctype/gui/DischargeTypeBrowser.java
- src/main/java/org/isf/disctype/gui/DischargeTypeBrowserEdit.java
See OP-1130
Changes for disctype package
Matching CORE PR: https://github.com/informatici/openhospital-core/pull/1115
> OP-1130 improve JPA methods - disctype package

- src/main/java/org/isf/menu/gui/Login.java
> OP-1138: catch NPE when user doesn't exist

- src/main/java/org/isf/distype/gui/DiseaseTypeBrowser.java
- src/main/java/org/isf/distype/gui/DiseaseTypeBrowserEdit.java
See OP-1130
Changes for distype package.
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1116
> OP-1130 improve JPA methods - distype package

- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowser.java
- src/main/java/org/isf/dlvrrestype/gui/DeliveryResultTypeBrowserEdit.java
See OP-1130
Matches changes in CORE PR: https://github.com/informatici/openhospital-core/pull/1117
> OP-1130 improve JPA methods - dlvrrestype package

- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowser.java
- src/main/java/org/isf/dlvrtype/gui/DeliveryTypeBrowserEdit.java
See OP-1130
Changes for dlvrtype package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1118
> OP-1130 improve JPA methods - dlvrtype package

- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
See OP-1130
Changes for exatype package
Matches the changes in CORE PR https://github.com/informatici/openhospital-core/pull/1119
> OP-1130 improve JPA methods - exatype package

- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/exa/gui/ExamEdit.java
- src/main/java/org/isf/exa/gui/ExamShow.java
See OP-1130
Changes for exa package
Matches the changes in CORE PR https://github.com/informatici/openhospital-core/pull/1120
> OP-1130 improve JPA methods - exa package

- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
See OP-1130
Changes for the disease package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1121
> OP-1130 improve JPA methods - disease package

- src/main/java/org/isf/menu/gui/Menu.java
> OP-1134 make gui auto find supporting font

- src/main/java/org/isf/examination/gui/PatientExaminationEdit.java
See OP-1130
Changes for examination package
Matches changes in CORE PR: https://github.com/informatici/openhospital-core/pull/1123
Majority of changes are code improvement related.
> OP-1130 improve JPA methods - examination package

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
See OP-1130
Changes for the medicals package
Matches the changes in CORE PR https://github.com/informatici/openhospital-core/pull/1131
> OP-1130 improve JPA methods - medicals package

- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
See OP-1130
Matches changes made in CORE PR https://github.com/informatici/openhospital-core/pull/1128
> OP-1130 improve JPA methods - lab package

- src/main/java/org/isf/malnutrition/gui/MalnutritionBrowser.java
See OP-1130
Changes for the malnutrition package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1130
> OP-1130 improve JPA methods - malnutrition package

- src/main/java/org/isf/medtype/gui/MedicalTypeBrowser.java
See OP-1130
Changes in `medtype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1138
> OP-1130 improve JPA methods - medtype package

- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/opd/gui/OpdBrowser.java
See OP-1130
Changes in `opd` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1139
> OP-1130 improve JPA methods - opd package

- src/main/java/org/isf/opetype/gui/OperationTypeBrowser.java
See OP-1130.
Changes for the `opetype` package.
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1142
> OP-1130 improve JPA methods - opetype package

- src/main/java/org/isf/pregtreattype/gui/PregnantTreatmentTypeBrowser.java
See OP-1130
Changes for `pregtreattytpe` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1143
> OP-1130 improve JPA methods - pregtreattype package

- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
See OP-1130
Changes for `vactype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1144
> OP-1130 improve JPA methods - vactype package

- src/main/java/org/isf/vaccine/gui/VaccineBrowser.java
See OP-1130
Changes for the `vaccine` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1145
> OP-1130 improve JPA methods - vaccine package

- src/main/java/org/isf/ward/gui/WardBrowser.java
See OP-1130
Changes for the `ward` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1146
> OP-1130 improve JPA methods - ward package

- src/main/java/org/isf/visits/gui/InsertVisit.java
See OP-1130
Changes for the `visits` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1147
No significant code changes; just watching the other package changes for this issue.
> OP-1130 improve JPA methods - visits package

- src/main/java/org/isf/therapy/gui/TherapyEdit.java
See OP-1130
Changes for the `therapy` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1148
> OP-1130 improve JPA methods - therapy package

- src/main/java/org/isf/sms/gui/SmsEdit.java
See OP-1130
Changes for the `sms` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1153
> OP-1130 improve JPA methods - sms package

- src/main/java/org/isf/supplier/gui/SupplierBrowser.java
- src/main/java/org/isf/supplier/gui/SupplierEdit.java
See OP-1130
Changes for the `supplier` package
Matches changes made in CORE PR https://github.com/informatici/openhospital-core/pull/1154
> OP-1130 improve JPA methods - supplier package

- src/main/java/org/isf/pricesothers/gui/PricesOthersBrowser.java
- src/main/java/org/isf/pricesothers/gui/PricesOthersEdit.java
See OP-1130
Changes for the `pricesothers` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1155
> OP-1130 improve JPA methods - pricesothers package

- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
See OP-1130
Changes for `patvac` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1157
> OP-1130 improve JPA methods - patvac package

- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
See OP-1130
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1158
> OP-1130 improve JPA methods - patconsensus package

- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/patient/gui/PatientBrowser.java
- src/main/java/org/isf/patient/gui/PatientInsert.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patient/gui/PatientSummary.java
- src/main/java/org/isf/patient/gui/SelectPatient.java
See OP-1130
Matches changes in https://github.com/informatici/openhospital-core/pull/1159
> OP-1130 improve JPA methods - patient package

- src/main/java/org/isf/dicom/gui/DicomGui.java
- src/main/java/org/isf/dicom/gui/DicomViewGui.java
See OP-1130
Changes in `dicom` package
Matches changes in https://github.com/informatici/openhospital-core/pull/1160
Fix spelling
> OP-1130 improve JPA methods - dicom package

- oh.bat
- oh.ps1
- oh.sh
Updatedb JAVA JRE and MariaDB package version (see https://github.com/informatici/openhospital/pull/205)
Upped OH version
> Package version update - JAVA / MariaDB

- pom.xml
Release Notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.31
Matches change in CORE
> Chore: upgrade to SpringFramework 5.3.31

- bundle/language_en.properties
- src/main/java/org/isf/operation/gui/OperationRowBase.java
See OP-1130
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1172
> OP-1130 improve JPA methods - operation package

- pom.xml
Release Notes:  https://github.com/spring-projects/spring-boot/releases/tag/v2.7.18
Matches change in CORE
> Chore: upgrade to Spring Boot 2.7.18

- src/main/java/org/isf/priceslist/gui/ListBrowser.java
- src/main/java/org/isf/priceslist/gui/PricesBrowser.java
See OP-1130
Changes for `priceslist` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1174
> OP-1130 improve JPA methods - priceslist package

- src/main/java/org/isf/menu/gui/GroupEdit.java
- src/main/java/org/isf/menu/gui/UserBrowsing.java
- src/main/java/org/isf/menu/gui/UserEdit.java
- src/main/java/org/isf/menu/gui/UserGroupBrowsing.java
See OP-1130
Changes for `menu` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1178
> OP-1130 improve JPA methods - menu package

- src/main/java/org/isf/medstockmovtype/gui/MedicalDsrStockMovementTypeBrowser.java
See OP-1130
Changes for `medstockmovtype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1182
> OP-1130 improve JPA methods - medstockmovtype package

- src/main/java/org/isf/operation/gui/OperationRowBase.java
> OP-1124-variable-operations-all-never-has-a-value-assigned 

- src/main/java/org/isf/medicalstockward/gui/WardPharmacyEdit.java
See OP-1130
Changes for `medicalstockward` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1187
> OP-1130 improve JPA methods - medicalstockward package

- src/main/java/org/isf/medicalstockward/gui/WardPharmacy.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyNew.java
- src/main/java/org/isf/medicalstockward/gui/WardPharmacyRectify.java
See OP-1130
Changes for `medicalstock` package
Matches changes for Core PR https://github.com/informatici/openhospital-core/pull/1189
Note: changes are for removing `this` and removing redundant parenthesis.
> OP-1130 improve JPA methods - medicalstock package

- src/main/java/org/isf/lab/gui/LabNew.java
> OH2-258 | Change the value of enum LaboratoryStatus in lowercase

- src/main/java/org/isf/admission/gui/AdmissionBrowser.java
- src/main/java/org/isf/admission/gui/AdmittedPatientBrowser.java
- src/main/java/org/isf/admission/gui/PatientDataBrowser.java
- src/main/java/org/isf/admission/gui/PatientFolderBrowser.java
- src/main/java/org/isf/disease/gui/DiseaseBrowser.java
- src/main/java/org/isf/disease/gui/DiseaseEdit.java
- src/main/java/org/isf/exa/gui/ExamBrowser.java
- src/main/java/org/isf/exa/gui/ExamEdit.java
- src/main/java/org/isf/exa/gui/ExamRowEdit.java
- src/main/java/org/isf/exa/gui/ExamShow.java
- src/main/java/org/isf/exatype/gui/ExamTypeBrowser.java
- src/main/java/org/isf/exatype/gui/ExamTypeEdit.java
- src/main/java/org/isf/lab/gui/LabBrowser.java
- src/main/java/org/isf/lab/gui/LabEdit.java
- src/main/java/org/isf/lab/gui/LabEditExtended.java
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/menu/gui/PrivilegeTree.java
See [OP-1075](https://openhospital.atlassian.net/browse/OP-1075)
Packages a to m
Includes other minor updates too.
[OP-1075]: https://openhospital.atlassian.net/browse/OP-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1075 remove old history tracking for packages a to m

- src/main/java/org/isf/opd/gui/OpdBrowser.java
- src/main/java/org/isf/opd/gui/OpdEdit.java
- src/main/java/org/isf/opd/gui/OpdEditExtended.java
- src/main/java/org/isf/operation/gui/OperationEdit.java
- src/main/java/org/isf/patient/gui/PatientInsertExtended.java
- src/main/java/org/isf/patvac/gui/PatVacBrowser.java
- src/main/java/org/isf/patvac/gui/PatVacEdit.java
- src/main/java/org/isf/stat/gui/report/GenericReportFromDateToDate.java
- src/main/java/org/isf/stat/gui/report/GenericReportMY.java
- src/main/java/org/isf/stat/gui/report/GenericReportUserInDate.java
- src/main/java/org/isf/stat/reportlauncher/gui/ReportLauncher.java
- src/main/java/org/isf/utils/jobjects/JAgenda.java
- src/main/java/org/isf/vaccine/gui/VaccineBrowser.java
- src/main/java/org/isf/vaccine/gui/VaccineEdit.java
- src/main/java/org/isf/vactype/gui/VaccineTypeBrowser.java
- src/main/java/org/isf/vactype/gui/VaccineTypeEdit.java
See [OP-1075](https://openhospital.atlassian.net/browse/OP-1075)
Packages o to m
Includes other minor updates too.
[OP-1075]: https://openhospital.atlassian.net/browse/OP-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1075 remove old history tracking for packages o to v

- src/main/java/org/isf/lab/gui/LabEdit.java
See OP-1162
Note: this was found when trying to get a screen shot to update the documentation.
> OP-1162 fix ArrayIndexOutOfBoundsException

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
> OP-1167 Add error for unexpected condition on lot management

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
See OP-1166.
Paired with https://github.com/informatici/openhospital-core/pull/1234.
> OP-1166 Fix lot validation

- bundle/language_en.properties
See OP-1137
Goes with https://github.com/informatici/openhospital-core/pull/1240
> OP-1137 new message for additional validation upon OPD save/update

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
> OP-1166 Fix lot preparation date time

- bundle/language_en.properties
- src/main/java/org/isf/help/LogViewer.java
- src/main/java/org/isf/utils/log/LogViewer.java
See OP-1168.
Paired with https://github.com/informatici/openhospital-core/pull/1241
> OP-1168 Add LogViewer

- pom.xml
> OP-1160 Replace rxtxserial.dll with jSerialComm library

- .github/workflows/maven.yml
Matches https://github.com/informatici/openhospital-core/pull/1250
> OP-1174 update maven.yml for JDK 17

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1176 | UPDATE warning message dialog to error message dialog

- oh.bat
- oh.ps1
- oh.sh
See OP-1129 and OP-1142.
Startup script updates and fixes.
> OP-1129 OP-1142 Script language update

- rsc/log4j.properties.dist
See OP-1179.
Paired with https://github.com/informatici/openhospital-core/pull/1267.
> OP-1179 Change DailyRollingFileAppender to RollingFileAppender

- oh.bat
- oh.ps1
- oh.sh
Hopefully last PR for https://openhospital.atlassian.net/browse/OP-1141
> OP-1141 - Demo credential fix

- bundle/language_en.properties
- src/main/java/org/isf/medicalinventory/gui/InventoryBrowser.java
- src/main/java/org/isf/utils/jobjects/InventoryState.java
- src/main/java/org/isf/utils/jobjects/InventoryStatus.java
See OP-1182.
Paired with https://github.com/informatici/openhospital-core/pull/1280.
> OP-1182 | Add Window to Manage global Inventory

- oh.bat
- oh.ps1
- oh.sh
- ohmac.sh
- pom.xml
See OP-1149
The main class is no longer `org.isf.menu.gui.Menu` but `org.isf.Application` so the Spring Boot class scanning will work.  The main class needs to be at the top of the tree for best results.
> OP-1149 The main class is no longer `org.isf.menu.gui.Menu` but `org.isf.Application`

- src/test/java/org/isf/accounting/gui/BillDataLoaderTest.java
See OP-1210
Without this temporary change the test will not compile.
Will make the **correct** fix as soon as I have the time; sorry for the breakage.
> OP-1210 quick "fix" for changes from CORE PR-1210.

- pom.xml
- src/test/java/org/isf/accounting/gui/BillDataLoaderTest.java
> OP-1230: re-enable tests

- src/test/java/org/isf/accounting/gui/BillDataLoaderTest.java
- src/test/java/org/isf/accounting/gui/TestBill.java
- src/test/java/org/isf/accounting/gui/TestPayment.java
- src/test/java/org/isf/accounting/gui/totals/BalanceTotalTest.java
- src/test/java/org/isf/accounting/gui/totals/PaymentsTotalTest.java
- src/test/java/org/isf/accounting/gui/totals/UserTotalTest.java
- src/test/java/org/isf/admission/gui/ward/WardBrowserManagerStub.java
- src/test/java/org/isf/admission/gui/ward/WardComboBoxInitializerTest.java
See OP-1235.
Paired with https://github.com/informatici/openhospital-core/pull/1326
Also fix naming test helper class conflicting with core
> OP-1235 Reflecting changes in CORE

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1229 Medicals sorted by name in Pharmaceutical Stock

- src/main/java/org/isf/medicals/gui/MedicalBrowser.java
See OP-1226.
- Fix CellRenderer using the actual showing data
- Fix MedicalBrowser filtering after edit
- Fix columns auto resizing in MedicalBrowser
> OP-1226 Fix MedicalBrowser style and filtering

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1228 Add product code column to Pharmaceutical Stock

- src/main/java/org/isf/medicals/gui/MedicalEdit.java
> OP-1225 Allow to change MedicalType

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1227 Show 2 decimals only for prices in Pharmaceutical Stock

- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
- src/main/java/org/isf/medicalstock/gui/MovStockMultipleDischarging.java
> OP-1219 Add Ward comparator to sort in combobox

- src/main/java/org/isf/medicalstock/gui/MovStockMultipleCharging.java
> OP-1220 Add Supplier comparator to sort in combobox

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1221 Improve filtering for all charge or discharge MovementType(s)

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1224 add reset button for pharmaceutical stock filter

- bundle/language_en.properties
- src/main/java/org/isf/medicalstock/gui/MovStockBrowser.java
> OP-1223 Improve Pharmaceutical Stock label and graphics
